# -*- coding: utf-8 -*-
"""
schema_comment_dict.py - 中文备注词典

用于给 DuckDB 表/字段自动生成中文备注。包含：
  1. TABLE_COMMENTS: 表级中文说明（核心表人工精确定义）
  2. COMMON_FIELDS:  通用字段词典（按字段名词干匹配）
  3. PREFIX_RULES:   常见前缀/标记字段的解释
  4. SUFFIX_RULES:   常见后缀的含义
  5. MANUAL_OVERRIDE: 核心表字段人工精确覆盖（最高优先级）

词典只负责"翻译"，写入 DuckDB 由 apply_schema_comments.py 完成。
"""

# ---------------- 表级中文说明 ----------------
TABLE_COMMENTS = {
    # --- CDC ---
    "_cdc_state": "同步状态汇总（各表CDC全量/增量同步状态）",
    # --- 销售 ---
    "SALEOUTMT": "销售出库主表（发货/出库环节，含税额销售额）",
    "SALEOUTDT": "销售出库明细表（通过BILLNO关联SALEOUTMT）",
    "SALENOTESMT": "销售单主表（接单环节，先下单后出库）",
    "SALENOTESDT": "销售单明细表（通过BILLNO关联SALENOTESMT）",
    "SALERTNMT": "销售退货主表",
    "SALERTNDT": "销售退货明细表",
    # --- 采购 ---
    "PURORDERMT": "采购订单主表",
    "PURORDERDT": "采购订单明细表",
    "PURINMT": "采购入库主表",
    "PURINDT": "采购入库明细表",
    # --- 库存 ---
    "ANGLEBALANCE": "货位库存余额表（当前库存/预警阈值）",
    "STORBALANCE": "仓库库存余额表",
    "BATCHCODE": "批次批号表（生产日期/有效期/价格）",
    "ZBKXKC": "质管科库存视图",
    "K_LSKC_DT": "零售库存快照",
    "K_LSXS_DT": "零售销量快照（7/10/15/30/60/90天）",
    # --- 商品 ---
    "GOODSDOC": "商品档案表（商品主数据）",
    "GOODSATTR": "商品属性表（280+列，含分类/资质/管制标记）",
    "GOODSOCCU": "商品占用记录表",
    "PGPRICE": "商品价格表（采购/销售/零售价）",
    "IMEIHIS": "序列号/溯源码历史表（药品追溯）",
    # --- 客户/往来 ---
    "CLIENTDOC": "客户档案表",
    "BUSINESSDOC": "往来单位档案表（客户/供应商/物流/门店）",
    "CONTACTDOC": "联系人档案表",
    "SUPPLYDOC": "供应商档案表",
    "STAFFDOC": "员工档案表",
    "STOREHOUSE": "仓库档案表（仓库/货位）",
    # --- 电商 ---
    "K_D3OMS_ORDERREFUNDMT": "电商退款主表（各平台退款订单）",
    "K_D3OMS_ORDERREFUNDDT": "电商退款明细表",
    "K_D3OMS_STOCKOUTMT_PLAN": "电商出库计划表（平台推送的发货计划）",
    "K_PRN_SENDLOG": "电商打印发货日志表",
    "RETBILLMT": "零售收银/零售单主表（门店零售）",
    "RETGOODSDT": "零售单商品明细表",
    "REQUESTMT": "要货申请主表（门店向仓库要货）",
    "REQUESTDT": "要货申请明细表",
    "TRBILLMT": "调拨单主表",
    "TRGOODSDT": "调拨单明细表",
    "SKWMS_JGM_W": "WMS近效期/结构管理接口表（定时同步）",
    "ZZERP_CK_KPD_W": "ERP出库看板图接口表（运营看板）",
    "ZZERP_GT_KPD_W": "ERP柜台看板图接口表（运营看板）",
    "ZZERP_RK_KPD_W": "ERP入库看板图接口表（运营看板）",
    "ZZERP_XT_KPD_W": "ERP协同看板图接口表（运营看板）",
    "chain_catalog": "连锁目录表（药商通/连锁体系）",

    # --- dim 维度表 ---
    "product": "商品维度表（标准化商品主数据）",
    "customer": "客户维度表（标准化客户主数据）",
    "warehouse": "仓库维度表（标准化仓库主数据）",
    "staff": "员工维度表（标准化员工主数据）",
    "supplier": "供应商维度表（标准化供应商主数据）",

    # --- agg 聚合表 ---
    "daily_sales": "日销售聚合表（按日期/仓库/客户/商品汇总）",
    "weekly_report": "周销售报表",
    "monthly_report": "月度销售报表",
    "kpi_realtime": "实时KPI指标表",
    "alert_inventory": "库存预警表",
    "data_audit": "数据对账审计表（源Oracle vs 目标DuckDB）",
    "c_retail_detail": "零售明细宽表（含电商平台订单、明细聚合宽表）",
}

# ---------------- 通用字段词典（按完整/子串匹配） ----------------
_COMMON_FIELD_MAP = {
    # --- 通用ID/编码 ---
    "BILLNO": "单据号",
    "BILLSN": "单据行号/序号",
    "BILLCODE": "单据编号",
    "BILLSORT": "单据类别",
    "BILLTYPE": "单据类型",
    "ENTID": "企业ID/账套标识",
    "OWNERID": "所有者ID",
    "ORGID": "组织ID",
    "DEPTID": "部门ID",
    "RULEID": "单据规则ID",
    "GOODSID": "商品ID",
    "PACKID": "包装ID",
    "ANGLEID": "货位ID",
    "LOCATID": "库位ID",
    "WHID": "仓库ID",
    "WHORGID": "仓库组织ID",
    "CLIENTID": "客户ID",
    "CLIENTCODE": "客户编码",
    "SALEMANID": "业务员ID",
    "STAFFID": "员工ID",
    "SUPPLIERSID": "供应商ID",
    "CONTACTID": "联系人ID",
    "CURRENCYID": "币种ID",
    "PAYORGID": "付款组织ID",
    "ACCPTID": "验收员ID",
    "BATCHCODE": "批号/批次",
    "BARCODE": "条形码",
    "CODE": "编码",
    # --- 日期时间 ---
    "DATES": "业务日期",
    "ONTIME": "业务时间",
    "SYSDATES": "系统日期/录入日期",
    "CREATETIME": "创建时间",
    "LASTMODIFYTIME": "最后修改时间",
    "DELTIME": "删除时间",
    "PRODUCEDATE": "生产日期",
    "VALDATE": "有效期至",
    "EXPECTDATE": "预计到货日期",
    "REQDATE": "要求日期",
    "WANTDATE": "期望到货日期",
    "ORDERDATE": "下单日期",
    "UPDATETIME": "更新时间",
    "PAYTIME": "付款时间",
    # --- 数量/金额 ---
    "NUM": "数量",
    "BASENUM": "基本单位数量",
    "PLACENUM": "货位库存数量",
    "PLACEPACK": "货位包装件数",
    "MIDNUM": "中间单位数量",
    "OCCUPNUM": "占用数量",
    "STORMAX": "最大库存量",
    "STORMIN": "最小库存量(预警阈值)",
    "STORFIT": "合理库存量",
    "AMOUNT": "金额(不含税)",
    "TAXAMOUNT": "含税金额",
    "TAX": "税额",
    "TAXPRICE": "含税单价",
    "PRICE": "单价",
    "RATE": "税率",
    "DEDRATE": "折扣率",
    "COSTAMT": "成本金额",
    "COST": "成本单价",
    "PROFIT": "毛利",
    "RETAILAMT": "零售金额",
    "RETAILP": "零售价",
    "PURP": "采购价",
    "PURTAXP": "含税采购价",
    "SALEP": "销售价",
    "SALETAXP": "含税销售价",
    "MEMPRICE": "会员价",
    "LISTPRICE": "挂牌价",
    "ACTPRICE": "实际单价",
    "ACTAMOUNT": "实际金额",
    "ACTPROFIT": "实际毛利",
    "ACTCOSTAMT": "实际成本金额",
    "ACTTAXPRICE": "实际含税单价",
    "OUTPRICE": "出库价",
    "OUTTAXPRICE": "含税出库价",
    "EXECNUM": "执行数量",
    "CANCELNUM": "取消数量",
    "RETURNNUM": "退货数量",
    "CHNUM": "差错数量",
    "SOLDNUM": "已售数量",
    "NOTSOLDNUM": "未售数量",
    "INVOICENUM": "开票数量",
    "INVOICEAMT": "开票金额",
    "RECAMT": "收款金额",
    "FUNAMT": "找零金额",
    "PAIDINAMT": "实收金额",
    "BALANCE": "余额",
    "AMTCOUNT": "金额笔数",
    "DTCOUNT": "明细笔数",
    # --- 标记/标志 ---
    "ISFREE": "是否赠送",
    "ISDONE": "是否完成",
    "ISEND": "是否已结束",
    "ISVAT": "是否增值税票",
    "ISINVOICE": "是否开票",
    "ISSALE": "是否销售",
    "ISPROCUR": "是否采购",
    "ISFREEZE": "是否冻结",
    "ISABANDON": "是否作废",
    "BEACTIVE": "是否启用",
    "ISACTIVE": "是否启用",
    "ISNEW": "是否新建",
    "BEACTIVE": "是否启用",
    "ISSALEPACK": "是否可售包装",
    "ISPURPACK": "是否可采包装",
    "ISRETPACK": "是否可退包装",
    "ISBASE": "是否基本单位",
    "ISWMS": "是否WMS管理",
    "ISELEC": "是否电商单",
    "ISPRES": "是否处方药",
    "ISOTC": "是否OTC药",
    "ISDRUG": "是否药品",
    "ISREFRIG": "是否需冷藏",
    "ISMEDICARE": "是否医保药品",
    "ISTRACE": "是否需追溯",
    # --- 名称/描述 ---
    "GOODSNAME": "商品名称",
    "GOODSCODE": "商品编码",
    "GOODSSPEC": "商品规格",
    "SHORTNAME": "简称",
    "FOREIGNNAME": "外文名",
    "SUMMARIES": "摘要",
    "REMARK": "备注",
    "CONTACT": "联系人",
    "TELEPHONE": "电话",
    "MOBILE": "手机",
    "FAX": "传真",
    "EMAIL": "邮箱",
    "ADDRESS": "地址",
    "PLACE": "产地",
    "MANUFACTURER": "生产企业",
    "UNIT": "单位",
    "MEAS": "包装含量/换算率",
    "GENERALNAME": "通用名",
    "CHEMNAME": "化学名",
    "COMMNAME": "商品通用名",
    "APPROVALNO": "批准文号",
    "GENERALNAME": "通用名",
    "TITLE": "标题/商品标题",
    "DEPTNAME": "部门名称",
    "POSNAME": "店铺名称/销售点",
    # --- 人员 ---
    "CAOZY": "操作员",
    "CREATERID": "创建人ID",
    "CREATERINFO": "创建人信息",
    "SALEMANNAME": "业务员名称",
    "STAFFNAME": "员工姓名",
    "POSITIONS": "职位",
    # --- 电商 ---
    "ORDERID": "电商平台订单ID",
    "REFOID": "平台订单号/参考单号",
    "ERP_ORDER_ID": "ERP订单ID",
    "LOGISTICSNO": "物流单号",
    "LOGISTICCODE": "物流编码",
    "LOGISTICSNAME": "物流公司名称",
    "EXPRESSCODE": "快递单号",
    "SHIPPERCODE": "发货方编码",
    "KDNORDERCODE": "快递鸟订单编码",
    "PLATFORM_ORDER_NO": "平台订单号",
    "PROVINCE": "省份",
    "CITY": "城市",
    "DISTRICT": "区县",
    "AREA": "区域",
    "RECEIVER": "收货人",
    "RECEIVERPHONE": "收货人电话",
    "REFUNDFEE": "退款金额",
    "REFUNDPHASE": "退款阶段",
    "ORDERSTATUS": "订单状态",
    "REFSPUID": "退款SPU ID",
    "REFSKUID": "退款SKU ID",
    # --- ETL ---
    "ETL_TIME": "ETL同步时间",
    "ETL_SOURCE": "ETL同步来源",
    "_ETL_TIME": "ETL同步时间",
    "_ETL_SOURCE": "ETL同步来源",
    # --- 通用时间/日期（多用于agg/dim驼峰命名） ---
    "SALE_DATE": "销售日期",
    "SALE_TIME": "销售时间",
    "CREATE_TIME": "创建时间",
    "UPDATE_TIME": "更新时间",
    "CURRENT_QTY": "当前库存数量",
    "THRESHOLD_QTY": "预警阈值数量",
    "ALERT_DATE": "预警日期",
    "ALERT_TIME": "预警时间",
    "ALERT_TYPE": "预警类型",
    "PRODUCT_NAME": "商品名称",
    "PRODUCT_ID": "商品ID",
    "PRODUCT_CODE": "商品编码",
    "CUSTOMER_ID": "客户ID",
    "CUSTOMER_CODE": "客户编码",
    "WAREHOUSE_ID": "仓库ID",
    "WAREHOUSE_CODE": "仓库编码",
    "WAREHOUSE_NAME": "仓库名称",
    "WAREHOUSE_TYPE": "仓库类型",
    "WAREHOUSE_LEVEL": "仓库等级",
    "SUPPLIER_ID": "供应商ID",
    "SUPPLIER_CODE": "供应商编码",
    "SUPPLIER_CATEGORY": "供应商类别",
    "SUPPLIER_LEVEL": "供应商等级",
    "SUPPLIER_TYPE": "供应商类型",
    "STAFF_ID": "员工ID",
    "STAFF_NAME": "员工姓名",
    "ORDER_COUNT": "订单数",
    "TOTAL_QTY": "销售数量",
    "TOTAL_AMOUNT": "销售金额",
    "TOTAL_COST": "销售成本",
    "GROSS_PROFIT": "毛利",
    "GROSS_MARGIN": "毛利率",
    "YEAR": "年份",
    "MONTH": "月份",
    "WEEK": "周",
    # --- 仓库/货位 ---
    "WHCODE": "仓库编码",
    "WHNAME": "仓库名称",
    "WHTYPE": "仓库类型",
    "WHLEVEL": "仓库等级",
    "AREASTATE": "区域状态",
    "DIRECTORID": "负责人ID",
    # --- 供应商/往来 ---
    "GYSBH": "供应商编号",
    "DUIKM": "对应科目",
    "SUPPCATE": "供应商类别",
    "SUPPLEV": "供应商等级",
    "SUPPTYPE": "供应商类型",
    "SUPPPROP": "供应商性质",
    # --- 员工 ---
    "USERID": "用户ID(企微/系统)",
    "STAFFCODE": "员工编码",
    "GENDER": "性别",
    "POSITION": "职位",
    "ORIGIN": "产地",
    "ERP_PRODUCT_NO": "ERP商品编号",
    "SALES_PERSON_ID": "销售人员ID",
    "ELECTRONIC_CODE": "电子监管码",
    "IS_SALES_CUSTOMER": "是否销售客户",
    "IS_ABANDONED": "是否作废",
    "SHORT_NAME": "简称",
    # --- CDC 状态表 ---
    "TABLE_NAME": "表名",
    "SYNC_MODE": "同步模式(全量/增量)",
    "LAST_SYNC_TIME": "最后同步时间",
    "LAST_CDC_TIME": "上次增量位点",
    "LAST_CDC_ID": "上次增量ID",
    "LAST_CDC_TS": "上次增量时间戳",
    "LAST_RECORD_COUNT": "本次同步行数",
    "ERROR_MSG": "错误信息",
    # 通用英文词（用于驼峰/多词拆分）
    "TABLE": "表",
    "NAME": "名称",
    "SYNC": "同步",
    "SEVERITY": "严重程度",
    "YEAR": "年份",
    "DATE": "日期",
    "TIME": "时间",
    "QTY": "数量",
    # --- ZZERP *_KPD_W 看板接口公共字段 ---
    "BUSINESSID": "往来单位ID",
    "OPERATOR": "操作员",
    "DEPT": "部门",
    "STAFF": "员工",
    "SUPERBILLNO": "上级单据号",
    "SUPERBILLCODE": "上级单据编号",
    "SUPERBILLSN": "上级行号",
    "FCLS": "返程类/组合类",
    "LCLS": "零散类",
    "LSS": "领料/零散类",
    "STOREFLAG": "门店标记",
    "DESIGNATED": "是否指定",
    "TWOINVOICE": "双发票标记",
    "URGENCY": "紧急程度",
    "STORETYPE": "仓库/门店类型",
    "PLATCODE": "平台编码",
    "SHIPPER": "发货方",
    "AUDITUSER": "审核人",
    "SECAUDITUSER": "二次审核人",
    "ZT": "状态",
    "CH_ZT": "签核状态",
    "FHTBH": "发货提单号",
    "OMS_DJBH": "OMS单据编号",
    "LOGISTICSCODE": "物流编码",
    "DS_BW": "电商部位",
    "DS_ZCW": "电商账务位",
    "SIGNATURE": "签名",
    "TEMPLATEURL": "模板URL",
    "BENDIAN": "本店标识",
    "DJTYPE": "单据类型",
    "ZSHL": "总数量/收货量",
    "BQTM": "标签条码",
    "XLH": "序列号",
    "LCLCODE": "零散编码",
    "YANSHR": "验收人",
}

# ---------------- 前缀规则（K_开头扩展字段、IS开头标志） ----------------
PREFIX_RULES = {
    "K_": "扩展字段",
    "IS": "是否",
}

# 需要翻译的 K_ 扩展字段精确映射
K_EXTRA = {
    "K_KDGS": "快递公司",
    "K_KDLXR": "快递联系人",
    "K_KDLXDH": "快递联系电话",
    "K_KDLXDZ": "快递联系地址",
    "K_KDDH": "快递单号",
    "K_PROVINCE": "省份",
    "K_CITY": "城市",
    "K_AREA": "区县",
    "K_ISREPORT": "是否报表",
    "K_ISPJ": "是否喷码",
    "K_ISWTS": "是否网厅送",
    "K_ISDB": "是否代播",
    "K_FHY": "复核员",
    "K_SHR": "审核人",
    "K_KPY": "开票员",
    "K_KPYID": "开票员ID",
    "K_KPBILLNO": "开票单据号",
    "K_KPBILLCODE": "开票单据编号",
    "K_KDDYRQ": "开单日期",
    "K_SWFLBM": "税务分类编码",
    "K_DRUGTRACE_OWNERID": "药品追溯所有者ID",
    "K_DRUGTRACE_ENTID": "药品追溯企业ID",
    "K_DRUGTRACE_REFENTID": "药品追溯参照企业ID",
    "K_ISKJ": "是否跨镜",
    "K_ZBZ": "总包装重",
    "K_ISTXYXQ": "是否特殊药药讯",
    "K_CWGM": "财务科目",
    "K_XSLB": "销售类别",
    "K_QQ": "逻辑量/扩展标识",
}

# ---------------- 手动覆盖（核心表字段，最高优先级） ----------------
# 格式: "表名.字段名": "中文备注"
MANUAL_OVERRIDE = {
    # SALEOUTMT 销售出库主表
    "SALEOUTMT.BILLNO": "主表单据号(主键)",
    "SALEOUTMT.BILLCODE": "单据编号",
    "SALEOUTMT.DATES": "业务日期(YYYY-MM-DD)",
    "SALEOUTMT.ONTIME": "业务时间",
    "SALEOUTMT.SYSDATES": "系统时间",
    "SALEOUTMT.CLIENTID": "客户ID",
    "SALEOUTMT.SALECLIENTID": "销售客户ID",
    "SALEOUTMT.SALEMANID": "业务员ID",
    "SALEOUTMT.AMOUNT": "不含税金额",
    "SALEOUTMT.TAX": "税额",
    "SALEOUTMT.TAXAMOUNT": "含税销售额(=平台实付)",
    "SALEOUTMT.PROFIT": "毛利",
    "SALEOUTMT.COSTAMT": "成本金额",
    "SALEOUTMT.RETAILAMT": "零售额",
    "SALEOUTMT.ISDONE": "是否完成(Y/N)",
    "SALEOUTMT.K_KDGS": "快递公司",
    "SALEOUTMT.K_KDDH": "快递单号",
    "SALEOUTMT.K_PROVINCE": "省份",
    "SALEOUTMT.K_CITY": "城市",
    "SALEOUTMT.REFOID": "电商平台订单号",
    "SALEOUTMT.POSNAME": "店铺名称",
    "SALEOUTMT.BILLSTATE": "单据状态",
    "SALEOUTMT.ORDERID": "电商订单ID",
    "SALEOUTMT.IS_DSTH": "是否电商退货",
    "SALEOUTMT.PAYTYPE": "付款方式",
    "SALEOUTMT.DELIVERY": "配送方式",
    "SALEOUTMT.INVOICE": "发票",
    "SALEOUTMT.INVOICETYPE": "发票类型",
    "SALEOUTMT.CONTRACTCODE": "合同号",
    "SALEOUTMT.CURCODE": "币种编码",
    "SALEOUTMT.PAIJIA": "牌价",
    "SALEOUTMT.ZJNUM": "件数",
    "SALEOUTMT.LSNUM": "零散数量",
    "SALEOUTMT.RECEMANID": "收货员ID",
    "SALEOUTMT.PICKUPMANID": "配货员ID",
    "SALEOUTMT.ACCEPTID": "验收员ID",
    "SALEOUTMT.FHYID": "复核员ID",
    "SALEOUTMT.SECACCEPTID": "二次验收员ID",
    "SALEOUTMT.ACCPTID": "验收员ID",
    "SALEOUTMT.WLDEPTID": "物流部门ID",
    "SALEOUTMT.SREASON": "销售原因",
    "SALEOUTMT.BUSICATE": "业务类别",
    "SALEOUTMT.INVOREQ": "开票要求",
    "SALEOUTMT.B2BCODE": "B2B编码",
    "SALEOUTMT.B2BTYPE": "B2B类型",
    "SALEOUTMT.DSCODE": "电商订单编码",
    "SALEOUTMT.DSTYPE": "电商订单类型",
    "SALEOUTMT.LOGISTICSNO": "物流单号",
    "SALEOUTMT.ISHTFH": "是否合同付费",
    "SALEOUTMT.ISHZFH": "是否货到后付费",
    "SALEOUTMT.OPPCONTID": "机会联系人ID",
    "SALEOUTMT.PZID": "凭证ID",
    "SALEOUTMT.KJ_YEAR": "会计年度",
    "SALEOUTMT.KJ_MONTH": "会计月份",
    "SALEOUTMT.ACTRP": "实际零售价",
    # ── 销售出库明细补充（退货/调价/成本） ──
    "SALEOUTDT.OUTCOST": "出库成本",
    "SALEOUTDT.RFBILLNO": "退货单据号",
    "SALEOUTDT.RFBILLSN": "退货行号",
    "SALEOUTDT.RFBILLCODE": "退货单编号",
    "SALEOUTDT.REBILLNO": "原销售单据号",
    "SALEOUTDT.REBILLSN": "原销售行号",
    "SALEOUTDT.REBILLCODE": "原销售单编号",
    "SALEOUTDT.RFRULEID": "退货规则ID",
    "SALEOUTDT.RERULEID": "原单据规则ID",
    "SALEOUTDT.OLDPRICE": "调价前单价",
    "SALEOUTDT.NEWPRICE": "调价后单价",
    "SALEOUTDT.OLDTAXPRICE": "调价前含税单价",
    "SALEOUTDT.NEWTAXPRICE": "调价后含税单价",
    "SALEOUTDT.BASEPRICE": "基本单位单价",
    "SALEOUTDT.BASETAXPRICE": "基本单位含税单价",
    "SALEOUTDT.OLDACTPRICE": "实际调价前单价",
    "SALEOUTDT.NEWACTPRICE": "实际调价后单价",
    "SALEOUTDT.OLDACTTAXPRICE": "实际调价前含税单价",
    "SALEOUTDT.NEWACTTAXPRICE": "实际调价后含税单价",
    "SALEOUTDT.FIXAMT": "固定金额",
    "SALEOUTDT.CONTRACTID": "合同ID",
    "SALEOUTDT.APID": "审批流ID",
    "SALEOUTDT.CHECKCOST": "核算成本",
    "SALEOUTDT.OUTACTCOST": "实际出库成本",
    "SALEOUTDT.BATCHNO": "批次号",
    "SALEOUTDT.GRPNO": "组合编号",
    # ── STORBALANCE 仓库库存表 ──
    "STORBALANCE.STORPACK": "库存件数",
    "STORBALANCE.STORNUM": "库存数量",
    "STORBALANCE.STORAMOUNT": "库存金额",
    "STORBALANCE.FINPACK": "结存件数",
    "STORBALANCE.FINNUM": "结存数量",
    "STORBALANCE.FINAMOUNT": "结存金额",
    "STORBALANCE.OLDPACK": "期初件数",
    "STORBALANCE.OLDNUM": "期初数量",
    "STORBALANCE.OLDAMOUNT": "期初金额",
    "STORBALANCE.PREPACK": "预付货件数",
    "STORBALANCE.PRENUM": "预付货数量",
    "STORBALANCE.PREAMOUNT": "预付货金额",
    "STORBALANCE.CARRCOST": "承运成本",
    "STORBALANCE.CHECKCOST": "核算成本",
    # ── GOODSATTR 商品属性（资质/分类/储存/医保/价格） ──
    "GOODSATTR.RECIPETYPE": "处方类型(处方/甲类OTC/乙类OTC/其他)",
    "GOODSATTR.MEDCARECODE": "医保编码",
    "GOODSATTR.MEDCARENAME": "医保名称",
    "GOODSATTR.STORAGETERM": "储存条件(常温/阴凉/冷藏/冷冻)",
    "GOODSATTR.REGNO": "注册证号/国药准字号",
    "GOODSATTR.REGVALDATE": "注册证有效期至",
    "GOODSATTR.GMPNO": "GMP证书号",
    "GOODSATTR.GMPVALDATE": "GMP有效期至",
    "GOODSATTR.INSTREGNO": "经营许可证号",
    "GOODSATTR.INSTREGDATE": "经营许可日期",
    "GOODSATTR.INSTREGVALDATE": "经营许可有效期至",
    "GOODSATTR.MFCREGNO": "生产企业许可证号",
    "GOODSATTR.MFCREGVALDATE": "生产企业许可有效期至",
    "GOODSATTR.APPROVALNO": "批准文号",
    "GOODSATTR.APPROVALDATE": "批准文号日期",
    "GOODSATTR.APPROVALTO": "批准文号有效期至",
    "GOODSATTR.REGYEARDATE": "注册年度日期",
    "GOODSATTR.RPTYEAR": "报告年度",
    "GOODSATTR.ONECATNAME": "一级类目名称",
    "GOODSATTR.TWOCATNAME": "二级类目名称",
    "GOODSATTR.THREECATNAME": "三级类目名称",
    "GOODSATTR.FOURCATNAME": "四级类目名称",
    "GOODSATTR.FIVECATNAME": "五级类目名称",
    "GOODSATTR.CATONE": "一级分类ID",
    "GOODSATTR.CATTWO": "二级分类ID",
    "GOODSATTR.CATTHREE": "三级分类ID",
    "GOODSATTR.STATCATE": "统计类别",
    "GOODSATTR.OPCAT": "运营类别",
    "GOODSATTR.MARKETCAT": "营销类别",
    "GOODSATTR.SOURCECAT": "来源类别",
    "GOODSATTR.PLANCATE": "计划类别",
    "GOODSATTR.GOODSGROUP": "商品分组ID",
    "GOODSATTR.MAINLEVEL": "主分类级别",
    "GOODSATTR.TREATCATE": "治疗类别",
    "GOODSATTR.GCATEGORY": "商品类别",
    "GOODSATTR.QCATEGORY": "质管类别",
    "GOODSATTR.KINDCODE": "类别编码",
    "GOODSATTR.KINDLCODE": "类别层级编码",
    "GOODSATTR.NKINDCODE": "新类别编码",
    "GOODSATTR.NKINDLCODE": "新类别层级编码",
    "GOODSATTR.MDLEVELNAME": "医保目录级别名称",
    "GOODSATTR.STANDCODE": "标准编码",
    "GOODSATTR.MEDCARETYPE": "医保类别",
    "GOODSATTR.ISBASEMED": "是否基本药物",
    "GOODSATTR.SAFEDAYS": "安全库存天数",
    "GOODSATTR.INEFFECTDAY": "失效天数",
    "GOODSATTR.DAYUNIT": "天数单位",
    "GOODSATTR.CURCYCLE": "当前周期",
    "GOODSATTR.SEASON": "季节",
    "GOODSATTR.FABRIC": "材质",
    "GOODSATTR.ACCES": "配件",
    "GOODSATTR.EXITDATE": "退出日期",
    "GOODSATTR.LIFETYPE": "寿命类型",
    "GOODSATTR.CONVRATIO": "换算率",
    "GOODSATTR.INTAXRATE": "进项税率",
    "GOODSATTR.OUTTAXRATE": "销项税率",
    "GOODSATTR.PURP": "采购价",
    "GOODSATTR.PURTAXP": "含税采购价",
    "GOODSATTR.SALEP": "销售价",
    "GOODSATTR.SALETAXP": "含税销售价",
    "GOODSATTR.RETAILP": "零售价",
    "GOODSATTR.LISTSALEP": "挂牌销售价",
    "GOODSATTR.MAXSALEP": "最高销售价",
    "GOODSATTR.MINSALEP": "最低销售价",
    "GOODSATTR.MAXRETAIP": "最高零售价",
    "GOODSATTR.MINRETAIP": "最低零售价",
    "GOODSATTR.ADRETAILP": "广告零售价",
    "GOODSATTR.BIDDPRICE": "投标价",
    "GOODSATTR.EXPRICE": "出口价",
    "GOODSATTR.INNERPRICE": "内部价",
    "GOODSATTR.DOWNPURP": "下调采购价",
    "GOODSATTR.WMSMEAS": "WMS换算率",
    "GOODSATTR.MULPOINT": "积分倍数",
    "GOODSATTR.PREPNSEPC": "预配包装换算",
    "GOODSATTR.PAIJIA": "牌价",
    "GOODSATTR.OUTPRICE": "出库价",
    "GOODSATTR.OUTTAXPRICE": "含税出库价",
    "GOODSATTR.KEMU": "会计科目",
    "GOODSATTR.INTERSCA": "内部评分",
    "GOODSATTR.TJ": "体积",
    "GOODSATTR.ARCHNO": "档案号",
    "GOODSATTR.LIMITNUM": "限购数量",
    "GOODSATTR.LIMITPURP": "限购价",
    "GOODSATTR.PRESLIMIT": "处方限购量",
    "GOODSATTR.WHOLLIMTNUM": "批发限购数量",
    "GOODSATTR.DEDUCTTYPE": "扣减类型",
    "GOODSATTR.DEDUCTRATE": "扣减率",
    "GOODSATTR.FORMULA": "配方/公式",
    "GOODSATTR.FORMULA_DL": "大料配方",
    "GOODSATTR.MANAGEPACK": "管理包装",
    "GOODSATTR.PREPNUNIT": "预配单位",
    "GOODSATTR.QUALSTAND": "质量标准",
    "GOODSATTR.REGMARK": "注册标记",
    "GOODSATTR.REGMARKVALTO": "注册标记有效期至",
    "GOODSATTR.ELECGOODSCODE": "电商商品编码",
    "GOODSATTR.ISPREG": "是否孕产妇用药",
    "GOODSATTR.TMRULEID": "特殊管理规则ID",
    "GOODSATTR.ISFORBCASH": "是否限现金",
    "GOODSATTR.MARKETBY": "营销方式",
    "GOODSATTR.MARKETBYADD": "营销方式补充",
    "GOODSATTR.STORCAT": "储运类别",
    "GOODSATTR.STORABC": "储运ABC分类",
    "GOODSATTR.STORSCAMAX": "储运安全库存上限",
    "GOODSATTR.STORSCAMIN": "储运安全库存下限",
    "GOODSATTR.LEVELID": "等级ID",
    "GOODSATTR.CENPURMODE": "集中采购方式",
    "GOODSATTR.PRCONLEV": "价格控制级别",
    "GOODSATTR.GSRCCATE": "货源类别",
    "GOODSATTR.TRANSTYPE": "运输类型",
    "GOODSATTR.TRANSTERM": "运输条件",
    "GOODSATTR.FIRSTSUPP": "首选供应商",
    "GOODSATTR.FIRSTSUPPNAME": "首选供应商名称",
    "GOODSATTR.TRAITS": "性状",
    "GOODSATTR.YSFHDATE": "验收复核日期",
    "GOODSATTR.LCLGROUP": "本地组",
    "GOODSATTR.FCLGROUP": "非本地组",
    "GOODSATTR.SPBH": "商品编号",
    "GOODSATTR.SPMCH": "商品名称(拼音)",
    "GOODSATTR.SPLB": "商品类别",
    # ── SALENOTESMT 销售单主表（补充） ──
    "SALENOTESMT.SALECLIENTID": "销售客户ID",
    "SALENOTESMT.ADVAMT": "预付金额",
    "SALENOTESMT.BILLSTATE": "单据状态",
    "SALENOTESMT.BILLSRC": "单据来源",
    "SALENOTESMT.GOODSGLIST": "商品明细列表",
    "SALENOTESMT.OLDBILLNO": "原单据号",
    "SALENOTESMT.ADDRESSID": "收货地址ID",
    "SALENOTESMT.SREASON": "销售原因",
    "SALENOTESMT.TPLBILLID": "模板单据ID",
    "SALENOTESMT.TPLDOCID": "模板文档ID",
    "SALENOTESMT.BUSINESSNAME": "往来单位名称",
    "SALENOTESMT.YWTYPE": "业务类型",
    "SALENOTESMT.DSCODE": "电商订单编码",
    "SALENOTESMT.DSTYPE": "电商订单类型",
    "SALENOTESMT.B2BCODE": "B2B编码",
    # ── PURINMT 采购入库（补充） ──
    "PURINMT.OLDERNO": "原订单号",
    "PURINMT.PREPAYAMT": "预付款金额",
    "PURINMT.WAREMANID": "仓管员ID",
    "PURINMT.CURCODE": "币种编码",
    "PURINMT.K_YWBS": "业务标识",
    "PURINMT.BEIZHU": "备注字段",
    # ── 退货表 SALERTNMT / RETBILLMT / RETGOODSDT ──
    "SALERTNMT.SALECLIENTID": "销售客户ID",
    "SALERTNMT.BILLSTATE": "单据状态",
    "SALERTNMT.BUSINESSNAME": "往来单位名称",
    "SALERTNMT.TPLBILLID": "模板单据ID",
    "SALERTNMT.TPLDOCID": "模板文档ID",
    "SALERTNMT.SREASON": "退货原因",
    "SALERTNMT.WLDEPTID": "物流部门ID",
    "SALERTNMT.OPPCONTID": "机会联系人ID",
    "RETBILLMT.SMALLNO": "小票号",
    "RETBILLMT.BUSITYPE": "业务类型",
    "RETBILLMT.ONHOUR": "营业小时",
    "RETBILLMT.WETHERID": "天气ID",
    "RETBILLMT.DISAMT": "折扣金额",
    "RETBILLMT.WIPAMT": "在制金额/WIP金额",
    "RETBILLMT.CHAAMT": "找零金额",
    "RETBILLMT.COPIES": "份数",
    "RETBILLMT.STATIONCODE": "门店编码",
    "RETBILLMT.ARRDAYID": "到达日ID",
    "RETBILLMT.DOCTOR": "医生姓名",
    "RETBILLMT.DOCTORID": "医生ID",
    "RETBILLMT.SAVEAMT": "节省金额",
    "RETBILLMT.OLDBALANCE": "期初余额",
    "RETBILLMT.POINT": "积分",
    "RETBILLMT.OLDPOINT": "期初积分",
    "RETBILLMT.REBILLNO": "原单据号",
    "RETBILLMT.REBILLCODE": "原单据编号",
    "RETBILLMT.RERULEID": "原单据规则ID",
    "RETBILLMT.RFBILLNO": "退款单据号",
    "RETBILLMT.RFBILLCODE": "退款单编号",
    "RETBILLMT.RFRULEID": "退款规则ID",
    "RETBILLMT.PROMID": "促销ID",
    "RETBILLMT.PRICEPROMID": "价格促销ID",
    "RETBILLMT.ECSHOPORDER": "电商店铺订单号",
    "RETBILLMT.ECSHOPORDER_OLD": "原电商店铺订单号",
    "RETBILLMT.ECSHOPJHCODE": "电商建议款编码",
    "RETBILLMT.ECSHOPBILLOCDE": "电商店铺单据编码",
    "RETBILLMT.ECSHOPCODE": "电商店铺编码",
    "RETBILLMT.ECSHOPNAME": "电商店铺名称",
    "RETBILLMT.LOGISTICSCODE": "物流编码",
    "RETGOODSDT.TRAPRICE": "柜台价",
    "RETGOODSDT.RECAMT": "收款金额",
    "RETGOODSDT.PAIDINAMT": "实收金额",
    "RETGOODSDT.TRAAMT": "柜台金额",
    "RETGOODSDT.ECSHOPORDER": "电商店铺订单号",
    "RETGOODSDT.IMEINOLIST": "序列号列表",
    # ── TRBILLMT 调拨单 / TRGOODSDT ──
    "TRBILLMT.SMALLNO": "小票号",
    "TRBILLMT.BUSITYPE": "业务类型",
    "TRBILLMT.ONHOUR": "营业小时",
    "TRBILLMT.WETHERID": "天气ID",
    "TRBILLMT.DISAMT": "折扣金额",
    "TRBILLMT.PROMID": "促销ID",
    "TRBILLMT.DOCTORID": "医生ID",
    "TRBILLMT.ECSHOPNAME": "电商店铺名称",
    "TRBILLMT.REBILLNO": "原单据号",
    # ── REQUESTMT/REQUESTDT 要货申请 ──
    "REQUESTMT.URGENCY": "紧急程度",
    "REQUESTMT.WANTDATE": "期望到货日期",
    "REQUESTMT.TIANS": "天数",
    "REQUESTMT.ISCJ": "是否采购",
    "REQUESTMT.XZ": "性质",
    "REQUESTMT.BILLSTATE": "单据状态",
    "REQUESTMT.KISAPP": "是否审批",
    "REQUESTMT.ISREFRIG": "是否冷藏",
    "REQUESTMT.QH_TYPE": "签核类型",
    "REQUESTDT.REASON": "申请原因",
    "REQUESTDT.TQLX": "提取类型",
    "REQUESTDT.ISTIQU": "是否已提取",
    "REQUESTDT.JY_NUM": "结余数量",
    "REQUESTDT.NUM_TIQU": "提取数量",
    "REQUESTDT.K_ISFD": "是否分配",
    "REQUESTDT.XSNUM7": "近7天销量",
    "REQUESTDT.XSNUM15": "近15天销量",
    "REQUESTDT.XSNUM30": "近30天销量",
    "REQUESTDT.XSNUM60": "近60天销量",
    "REQUESTDT.PFNUM": "批发数量",
    "REQUESTDT.PLACENUM": "货位数量",
    "REQUESTDT.ORGNUM": "组织数量",
    # ── IMEIHIS 序列号/追溯 ──
    "IMEIHIS.IMEINO": "序列号/IMEI号",
    "IMEIHIS.RFID": "RFID标签号",
    "IMEIHIS.RFTYPE": "RFID类型",
    "IMEIHIS.OLDSTATE": "原状态",
    "IMEIHIS.NEWSTATE": "新状态",
    "IMEIHIS.BUSIATTR": "业务属性",
    "IMEIHIS.PELECCODE": "电子监管码",
    "IMEIHIS.ISSUBLINK": "是否子关联",
    "IMEIHIS.CODELEVEL": "码级别",
    "IMEIHIS.PHYSICTYPE": "物理类型",
    "IMEIHIS.PKGRATIO": "包装比例",
    "IMEIHIS.IMEISTATE": "序列号状态",
    "IMEIHIS.IMEIDESC": "序列号描述",
    "IMEIHIS.RFNAME": "RF操作名称",
    "IMEIHIS.OPPCONTACT": "对方联系人",
    "IMEIHIS.SALEMANNAME": "业务员名称",
    "IMEIHIS.RPTSTATUS": "报表状态",
    "IMEIHIS.RPTELECTYPE": "报表电子类型",
    "IMEIHIS.TYPESIGN": "类型标识",
    "IMEIHIS.SYSDATES": "系统日期",
    "IMEIHIS.UDICODE": "UDI编码",
    # ── 电商退款明细 K_D3OMS_ORDERREFUNDDT ──
    "K_D3OMS_ORDERREFUNDDT.ERP_ORDER_ID": "ERP订单ID",
    "K_D3OMS_ORDERREFUNDDT.ERP_ORDER_SN": "ERP订单序号",
    "K_D3OMS_ORDERREFUNDDT.REFAID": "退款单ID",
    "K_D3OMS_ORDERREFUNDDT.REFOID": "退款单号",
    "K_D3OMS_ORDERREFUNDDT.REFSPUID": "退款SPU ID",
    "K_D3OMS_ORDERREFUNDDT.REFSKUID": "退款SKU ID",
    "K_D3OMS_ORDERREFUNDDT.OUTERID": "外部订单ID",
    "K_D3OMS_ORDERREFUNDDT.TITLE": "商品标题",
    "K_D3OMS_ORDERREFUNDDT.NUM": "退款数量",
    "K_D3OMS_ORDERREFUNDDT.PRICE": "单价",
    "K_D3OMS_ORDERREFUNDDT.TOTALFEE": "订单总金额",
    "K_D3OMS_ORDERREFUNDDT.REFUNDFEE": "退款金额",
    # ── 电商出库计划 K_D3OMS_STOCKOUTMT_PLAN（补充） ──
    "K_D3OMS_STOCKOUTMT_PLAN.TAG": "标签",
    "K_D3OMS_STOCKOUTMT_PLAN.CODE": "编码",
    "K_D3OMS_STOCKOUTMT_PLAN.TYPE": "类型",
    "K_D3OMS_STOCKOUTMT_PLAN.REFOID": "退款/来源单号",
    "K_D3OMS_STOCKOUTMT_PLAN.POSCODE": "店铺编码",
    "K_D3OMS_STOCKOUTMT_PLAN.K_F_REASON": "发货原因",
    "K_D3OMS_STOCKOUTMT_PLAN.SELLERMEMO": "卖家备注",
    "K_D3OMS_STOCKOUTMT_PLAN.BUYERMEMO": "买家备注",
    # ── SALENOTESDT 销售单明细（与SALEOUTDT同构的退货/调价字段） ──
    "SALENOTESDT.OLDPRICE": "调价前单价",
    "SALENOTESDT.NEWPRICE": "调价后单价",
    "SALENOTESDT.OLDTAXPRICE": "调价前含税单价",
    "SALENOTESDT.NEWTAXPRICE": "调价后含税单价",
    "SALENOTESDT.OUTCOST": "出库成本",
    "SALENOTESDT.RFBILLNO": "退货单据号",
    "SALENOTESDT.RFBILLSN": "退货行号",
    "SALENOTESDT.REBILLNO": "原单据号",
    "SALENOTESDT.REBILLSN": "原行号",
    "SALENOTESDT.BASEPRICE": "基本单位单价",
    "SALENOTESDT.BASETAXPRICE": "基本单位含税单价",
    "SALENOTESDT.RFBILLCODE": "退货单编号",
    "SALENOTESDT.REBILLCODE": "原单编号",
    "SALENOTESDT.RFRULEID": "退货规则ID",
    "SALENOTESDT.RERULEID": "原单据规则ID",
    "SALENOTESDT.PROMID": "促销ID",
    "SALENOTESDT.GRPNO": "组合编号",
    "SALENOTESDT.STERILCODE": "灭菌批号",
    "SALENOTESDT.CHECKCOST": "核算成本",
    "SALENOTESDT.OLDACTPRICE": "实际调价前单价",
    "SALENOTESDT.NEWACTPRICE": "实际调价后单价",
    "SALENOTESDT.OLDACTTAXPRICE": "实际调价前含税单价",
    "SALENOTESDT.NEWACTTAXPRICE": "实际调价后含税单价",
    "SALENOTESDT.OUTACTCOST": "实际出库成本",
    "SALENOTESDT.BTGRPID": "批次组ID",
    "SALENOTESDT.BATCHNO": "批次号",
    "SALENOTESDT.PRICEFROM": "价格来源",
    "SALENOTESDT.PASSUSERID": "审核人ID",
    "SALENOTESDT.PASSEXPID": "审核人费用ID",
    "SALENOTESDT.TOPKGNUM": "顶层包装数量",
    "SALENOTESDT.TPLROWID": "模板行ID",
    "SALENOTESDT.TPLDOCID": "模板文档ID",
    "SALENOTESDT.GOODSREF": "商品参考",
    "SALENOTESDT.MARKETBY": "营销方式",
    "SALENOTESDT.INSTREGNO": "经营许可证号",
    "SALENOTESDT.INSTBY": "经营批准单位",
    # ── TRBILLMT 调拨单（医保/零售共通字段） ──
    "TRBILLMT.PAIJIA": "牌价",
    "TRBILLMT.WIPAMT": "在制金额/WIP金额",
    "TRBILLMT.CHAAMT": "找零金额",
    "TRBILLMT.COPIES": "份数",
    "TRBILLMT.STATIONCODE": "门店编码",
    "TRBILLMT.ARRDAYID": "到达日ID",
    "TRBILLMT.GUARDSN": "银联商户序号",
    "TRBILLMT.GUARDCODE": "银联商户代码",
    "TRBILLMT.CARDID": "卡ID(会员卡/医保卡)",
    "TRBILLMT.DOCTOR": "医生姓名",
    "TRBILLMT.SAVEAMT": "节省金额",
    "TRBILLMT.OLDBALANCE": "期初余额",
    "TRBILLMT.POINT": "积分",
    "TRBILLMT.OLDPOINT": "期初积分",
    "TRBILLMT.IDCARD": "身份证号",
    "TRBILLMT.REBILLCODE": "原单据编号",
    "TRBILLMT.RERULEID": "原单据规则ID",
    "TRBILLMT.RFBILLNO": "退款单据号",
    "TRBILLMT.RFBILLCODE": "退款单编号",
    "TRBILLMT.RFRULEID": "退款规则ID",
    "TRBILLMT.MICBILLCODE": "医保单据编号",
    "TRBILLMT.CARDSRC": "卡来源",
    "TRBILLMT.TRAAMT": "柜台金额",
    "TRBILLMT.ZHRAMT": "账户金额",
    "TRBILLMT.TOKENAMT": "代金券金额",
    "TRBILLMT.POTAMT": "积分金额",
    "TRBILLMT.PRICEPROMID": "价格促销ID",
    "TRBILLMT.HOMECONID": "家庭医生签约ID",
    "TRBILLMT.TREATDOCTID": "主治医生ID",
    "TRBILLMT.TREATASSID": "接诊护士ID",
    "TRBILLMT.TREATDEPTID": "就诊科室ID",
    "TRBILLMT.GHBILLNO": "挂号单号",
    "TRBILLMT.GHBILLCODE": "挂号单编号",
    "TRBILLMT.MICBILLDATE": "医保单据日期",
    "TRBILLMT.SETL_ID": "结算ID",
    "TRBILLMT.MDTRT_CERT_TYPE": "医保就医凭证类型",
    "TRBILLMT.PAYCAT": "支付类别",
    "TRBILLMT.ECSHOPORDER": "电商店铺订单号",
    "TRBILLMT.ECSHOPORDER_OLD": "原电商店铺订单号",
    "TRBILLMT.ECSHOPJHCODE": "电商建议款编码",
    "TRBILLMT.ECSHOPBILLOCDE": "电商店铺单据编码",
    "TRBILLMT.ECSHOPCODE": "电商店铺编码",
    "TRBILLMT.LOGISTICSCODE": "物流编码",
    # ── RETGOODSDT 零售单明细（补充） ──
    "RETGOODSDT.CHECKCOST": "核算成本",
    "RETGOODSDT.TEAM": "班组",
    "RETGOODSDT.DISAVGAMT": "折扣平均金额",
    "RETGOODSDT.WIPAVGAMT": "WIP平均金额",
    "RETGOODSDT.ZHRAVGAMT": "账户平均金额",
    "RETGOODSDT.TOKENAVGAMT": "代金券平均金额",
    "RETGOODSDT.POTAVGAMT": "积分平均金额",
    "RETGOODSDT.REBILLNO": "原单据号",
    "RETGOODSDT.REBILLCODE": "原单据编号",
    "RETGOODSDT.RERULEID": "原单据规则ID",
    "RETGOODSDT.REBILLSN": "原行号",
    "RETGOODSDT.PASSUSERID": "审核人ID",
    "RETGOODSDT.PASSEXPID": "审核人费用ID",
    "RETGOODSDT.ECSHOPBILLSN": "电商店铺单据行号",
    "RETGOODSDT.ECSHOPORDER_OLD": "原电商店铺订单号",
    "RETGOODSDT.ECSHOPBILLOCDE": "电商店铺单据编码",
    # ── SALERTNMT 销售退货主表 ──
    "SALERTNMT.PAIJIA": "牌价",
    "SALERTNMT.CONTRACTCODE": "合同号",
    "SALERTNMT.INVOICE": "发票",
    "SALERTNMT.PAYTYPE": "付款方式",
    "SALERTNMT.BUSICATE": "业务类别",
    "SALERTNMT.B2BCODE": "B2B编码",
    "SALERTNMT.DSTYPE": "电商订单类型",
    "SALERTNMT.DSCODE": "电商订单编码",
    "SALERTNMT.APID": "审批流ID",
    # ── PURORDERMT 采购订单（补充） ──
    "PURORDERMT.CONTRACTCODE": "合同号",
    "PURORDERMT.DELIVERY": "配送方式",
    "PURORDERMT.PAYTYPE": "付款方式",
    "PURORDERMT.OLDERNO": "原订单号",
    "PURORDERMT.BILLSTATE": "单据状态",
    "PURORDERMT.OPPCONTID": "机会联系人ID",
    "PURORDERMT.GOODSGLIST": "商品明细列表",
    "PURORDERMT.WLDEPTID": "物流部门ID",
    "PURORDERMT.BUSICATE": "业务类别",
    "PURORDERMT.BUSINESSNAME": "往来单位名称",
    "PURORDERMT.K_YWBS": "业务标识",
    "PURORDERMT.BEIZHU": "备注字段",
    "PURORDERMT.APID": "审批流ID",
    # ── PURINMT 采购入库（再补） ──
    "PURINMT.CONTRACTCODE": "合同号",
    "PURINMT.INVOICE": "发票",
    "PURINMT.DELIVERY": "配送方式",
    "PURINMT.PAYTYPE": "付款方式",
    "PURINMT.PAIJIA": "牌价",
    "PURINMT.OPPCONTID": "机会联系人ID",
    "PURINMT.WLDEPTID": "物流部门ID",
    "PURINMT.BUSICATE": "业务类别",
    "PURINMT.FHYID": "复核员ID",
    "PURINMT.SECACCEPTID": "二次验收员ID",
    "PURINMT.ACCEPTID": "验收员ID",
    "PURINMT.APID": "审批流ID",
    # ── CLIENTDOC 客户档案 ──
    "CLIENTDOC.DUIYKM": "对应科目",
    "CLIENTDOC.YWYID": "业务员ID",
    "CLIENTDOC.CLIENTTYPE": "客户类型",
    "CLIENTDOC.CLIENTSORT": "客户分类",
    "CLIENTDOC.ELECCODE": "电商编码",
    "CLIENTDOC.OLDCLIENTCODE": "原客户编码",
    "CLIENTDOC.CREDIT": "信用额度",
    "CLIENTDOC.INVOICETYPE": "发票类型",
    "CLIENTDOC.ORGTYPE": "组织类型",
    "CLIENTDOC.DRUGSTOREID": "药房ID",
    # ── PGPRICE 商品价格 ──
    "PGPRICE.LENGTH": "长",
    "PGPRICE.WIDE": "宽",
    "PGPRICE.HIGH": "高",
    "PGPRICE.BULKS": "体积",
    "PGPRICE.WEIGHT": "重量",
    "PGPRICE.ZYPACKID": "中药包装ID",
    "PGPRICE.ELECFLAG": "电商标记",
    # ── IMEIHIS 序列号补 ──
    "IMEIHIS.SERIALNUM": "序列号序号",
    "IMEIHIS.RANDOMID": "随机ID",
    "IMEIHIS.RPTBILLNO": "报表单据号",
    "IMEIHIS.RPTRULEID": "报表规则ID",
    "IMEIHIS.RPTBILLCODE": "报表单据编码",
    "IMEIHIS.RPTBILLSN": "报表行号",
    # ── GOODSOCCU 商品占用 ──
    "GOODSOCCU.BTGRPID": "批次组ID",
    "GOODSOCCU.BATCHNO": "批次号",
    "GOODSOCCU.CAOZY": "操作员",
    "GOODSOCCU.BUSICATE": "业务类别",
    # ── GOODSDOC 补 ──
    "GOODSDOC.DUIYKM": "对应科目",
    "GOODSDOC.OLDCODE": "原编码",
    "GOODSDOC.REMARK": "备注",
    # ── TRGOODSDT 调拨明细 ──
    "TRGOODSDT.TRAPRICE": "调拨价",
    "TRGOODSDT.CHECKCOST": "核算成本",
    "TRGOODSDT.PROMID": "促销ID",
    "TRGOODSDT.TEAM": "班组",
    "TRGOODSDT.DISAVGAMT": "折扣平均金额",
    "TRGOODSDT.WIPAVGAMT": "WIP平均金额",
    "TRGOODSDT.ZHRAVGAMT": "账户平均金额",
    "TRGOODSDT.TOKENAVGAMT": "代金券平均金额",
    "TRGOODSDT.POTAVGAMT": "积分平均金额",
    "TRGOODSDT.REBILLNO": "原单据号",
    "TRGOODSDT.REBILLCODE": "原单据编号",
    "TRGOODSDT.RERULEID": "原单据规则ID",
    "TRGOODSDT.REBILLSN": "原行号",
    "TRGOODSDT.PASSUSERID": "审核人ID",
    "TRGOODSDT.PASSEXPID": "审核人费用ID",
    "TRGOODSDT.ECSHOPBILLSN": "电商店铺单据行号",
    "TRGOODSDT.ECSHOPORDER": "电商店铺订单号",
    "TRGOODSDT.ECSHOPORDER_OLD": "原电商店铺订单号",
    "TRGOODSDT.ECSHOPBILLOCDE": "电商店铺单据编码",
    "TRGOODSDT.IMEINOLIST": "序列号列表",
    "TRGOODSDT.TRAAMT": "调拨金额",
    "TRGOODSDT.PRICEPROMID": "价格促销ID",
    # ── SALERTNDT 销售退货明细 ──
    "SALERTNDT.BASEPRICE": "基本单位单价",
    "SALERTNDT.BASETAXPRICE": "基本单位含税单价",
    "SALERTNDT.REBILLCODE": "原单据编号",
    "SALERTNDT.REBILLSN": "原行号",
    "SALERTNDT.RERULEID": "原单据规则ID",
    "SALERTNDT.REBILLNO": "原单据号",
    "SALERTNDT.CONTRACTID": "合同ID",
    "SALERTNDT.APID": "审批流ID",
    "SALERTNDT.BATCHNO": "批次号",
    "SALERTNDT.TPLROWID": "模板行ID",
    "SALERTNDT.TPLDOCID": "模板文档ID",
    "SALERTNDT.GOODSREF": "商品参考",
    "SALERTNDT.MARKETBY": "营销方式",
    "SALERTNDT.INSTREGNO": "经营许可证号",
    "SALERTNDT.INSTBY": "经营批准单位",
    # ── RETBILLMT 零售单（末批） ──
    "RETBILLMT.PAIJIA": "牌价",
    "RETBILLMT.GUARDCODE": "银联商户代码",
    "RETBILLMT.GUARDSN": "银联商户序号",
    "RETBILLMT.CARDID": "卡ID(会员卡/医保卡)",
    "RETBILLMT.IDCARD": "身份证号",
    "RETBILLMT.MICBILLCODE": "医保单据编号",
    "RETBILLMT.CARDSRC": "卡来源",
    "RETBILLMT.TRAAMT": "柜台金额",
    "RETBILLMT.ZHRAMT": "账户金额",
    "RETBILLMT.TOKENAMT": "代金券金额",
    "RETBILLMT.POTAMT": "积分金额",
    "RETBILLMT.HOMECONID": "家庭医生签约ID",
    "RETBILLMT.TREATDOCTID": "主治医生ID",
    "RETBILLMT.TREATASSID": "接诊护士ID",
    "RETBILLMT.TREATDEPTID": "就诊科室ID",
    "RETBILLMT.GHBILLNO": "挂号单号",
    "RETBILLMT.GHBILLCODE": "挂号单编号",
    "RETBILLMT.MICBILLDATE": "医保单据日期",
    "RETBILLMT.SETL_ID": "结算ID",
    "RETBILLMT.MDTRT_CERT_TYPE": "医保就医凭证类型",
    "RETBILLMT.PAYCAT": "支付类别",
    "RETBILLMT.EXBILLNO": "外部门店单据号",
    # ── chain_catalog 连锁目录 ──
    "chain_catalog.goods_spec": "商品规格",
    "chain_catalog.b2c_cgy": "B2C采购类目",
    "chain_catalog.formula": "配方/公式",
    "chain_catalog.approval_no": "批准文号",
    "chain_catalog.approval_to": "批准文号有效期至",
    "chain_catalog.med_care_type": "医保类别",
    "chain_catalog.bzjs": "包装件数",
    "chain_catalog.cat_level1": "一级类目",
    "chain_catalog.cat_level2": "二级类目",
    "chain_catalog.cat_level3": "三级类目",
    "chain_catalog.cat_level4": "四级类目",
    "chain_catalog.cat_level5": "五级类目",
    "chain_catalog.k_isqh": "是否签核扩展",
    "chain_catalog.k_cgsx": "采购属性扩展",
    "chain_catalog.inbound_supplier": "入库供应商",
    "chain_catalog.delivery_30d": "30天发货量",
    "chain_catalog.store_sales_30d": "门店30天销量",
    "chain_catalog.store_sales_60d": "门店60天销量",
    "chain_catalog.store_sales_90d": "门店90天销量",
    "chain_catalog.turnover_days": "周转天数",
    "chain_catalog.k_gwj": "供应价扩展",
    "chain_catalog.shortage_7d": "7天缺货量",
    # ── K_PRN_SENDLOG 打印发货日志 ──
    "K_PRN_SENDLOG.GUID": "全局唯一ID",
    "K_PRN_SENDLOG.CONTENT": "内容/报文",
    "K_PRN_SENDLOG.DHTYPE": "代号类型",
    "K_PRN_SENDLOG.MARKDESTINATION": "标记目的地",
    "K_PRN_SENDLOG.ORIGINNAME": "始发地名称",
    "K_PRN_SENDLOG.PACKAGENAME": "包裹名称",
    "K_PRN_SENDLOG.ORIGINCODE": "始发地编码",
    "K_PRN_SENDLOG.PACKAGECODE": "包裹编码",
    "K_PRN_SENDLOG.SORTINGCODE": "分拣编码",
    "K_PRN_SENDLOG.DESTINATIONAME": "目的地名称",
    "K_PRN_SENDLOG.DESTINATIOCODE": "目的地编码",
    # ── SKWMS_JGM_W WMS近效期接口 ──
    "SKWMS_JGM_W.TRAN_TYPE": "事务类型",
    "SKWMS_JGM_W.TRAN_SN": "事务序号",
    "SKWMS_JGM_W.IMEINO": "序列号",
    "SKWMS_JGM_W.ZT": "状态",
    "SKWMS_JGM_W.ID": "主键ID",
    "SKWMS_JGM_W.BENDIAN": "本店标识",
    # ── GOODSATTR 剩余非K_字段 ──
    "GOODSATTR.HESID": "医保结算ID",
    "GOODSATTR.ACCTLEVEL": "核算级别/科目级别",
    "GOODSATTR.ANGLETYPE": "货位类型",
    "GOODSATTR.SCHEMAID": "架构ID",
    "GOODSATTR.YEARSNUM": "年限",
    "GOODSATTR.RTNFLAG": "退货标记",
    "GOODSATTR.SALETYPE": "销售类型",
    "GOODSATTR.APPEARDATE": "上市日期",
    "GOODSATTR.DFTWHID": "默认仓库ID",
    "GOODSATTR.DFTLOCATID": "默认库位ID",
    "GOODSATTR.SDATE": "生效日期",
    "GOODSATTR.EDATE": "失效日期",
    "GOODSATTR.INSTBY": "经营批准单位",
    "GOODSATTR.STORAGEMEMO": "储存说明",
    "GOODSATTR.TEMPLATEID": "模板ID",
    "GOODSATTR.TAXCATE": "税务类别",
    "GOODSATTR.TAXNAME": "税目名称",
    "GOODSATTR.TAXCODE": "税目编码",
    "GOODSATTR.TPLDOCID": "模板文档ID",
    "GOODSATTR.CATRULE": "分类规则",
    "GOODSATTR.GOODSPURPOSE": "商品用途",
    "GOODSATTR.BZJS": "包装换算",
    "GOODSATTR.STORATTENTION": "储运注意事项",
    "GOODSATTR.JFBL": "计费比例",
    "GOODSATTR.JGCL": "价格策略/价格处理",
    "GOODSATTR.OUTBL": "出库比例",
    "STOREHOUSE.LOGOGRAM": "仓库简称/标识",
    "SUPPLYDOC.ELECCODE": "电商编码",
    "SUPPLYDOC.GYSBH": "供应商编号",
    "STAFFDOC.LOGOGRAM": "员工简称",
    "STAFFDOC.MOBILE": "手机号",
    "STAFFDOC.ISSALEMAN": "是否业务员",
    "STAFFDOC.ISPROCURMAN": "是否采购员",
    "STAFFDOC.ISWARE": "是否仓管员",
    "STAFFDOC.ISSETTLE": "是否结算员",
    "STAFFDOC.ISEXAMINE": "是否审核员",
    "STAFFDOC.STATE": "状态",
    "STAFFDOC.POSITIONS": "职位",
    "STAFFDOC.WORKSTATUS": "工作状态",
    "STAFFDOC.HIREDATE": "入职日期",
    "STAFFDOC.LEAVEDATE": "离职日期",
    "STAFFDOC.SALARY": "薪资",
    "STAFFDOC.DEPTID": "部门ID",
    "STAFFDOC.ORGID": "组织ID",
    "STAFFDOC.OWNERID": "所有者ID",
    "STAFFDOC.ENTID": "企业ID",
    "STAFFDOC.BEACTIVE": "是否启用",
    "STAFFDOC.REMARK": "备注",
    # ── CONTACTDOC 联系人档案（DBA字典未提供，按字段名补充能确定的） ──
    "CONTACTDOC.GROUPID": "集团/客户分组ID",
    "CONTACTDOC.CONTACTCODE": "联系人编码",
    "CONTACTDOC.LOGOGRAM": "助记码/简称",
    "CONTACTDOC.IDCARD": "身份证号",
    "CONTACTDOC.POSTCODE": "邮编",
    "CONTACTDOC.BIRTHDAY": "生日",
    "CONTACTDOC.FAVORITE": "偏好/喜好",
    "CONTACTDOC.SKILL": "专长",
    "CONTACTDOC.XYLEVEL": "信用等级",
    "CONTACTDOC.KOUL": "扣率",
    "CONTACTDOC.LEVELID": "等级ID",
    "CONTACTDOC.QUANZH": "权重/权限",
    "CONTACTDOC.DOCLEVID": "资料权限级别ID",
    "CONTACTDOC.EXPAUTORG": "扩展授权机构",
    "CONTACTDOC.RESAUTORG": "授权限制机构",
    "CONTACTDOC.DELUSERID": "信息删除人",
    "CONTACTDOC.SOURCES": "信息来源",
    "CONTACTDOC.PERIOD": "周期/账期",
    "CONTACTDOC.BUSINTYPE": "业务类型",
    "CONTACTDOC.CONSCERT": "联系人证件",
    "CONTACTDOC.CONSCERTDATE": "联系人证件日期",
    "CONTACTDOC.CONSMANDATE": "联系人授权书/委托书",
    "CONTACTDOC.CONTYPE": "联系人类型",
    "CONTACTDOC.CONSCOPE": "经营范围",
    "CONTACTDOC.ATTACHID": "附件ID",
    "CONTACTDOC.QQ": "QQ号",
    "CONTACTDOC.FETIONADD": "飞信号/联系方式",
    "CONTACTDOC.CREDULITY": "信任度/信用度",
    "CONTACTDOC.MICROINFO": "微信信息",
    "CONTACTDOC.CONSMANNO": "委托人编号/联系人编号",
    "CONTACTDOC.BBSUSERID": "论坛用户ID",
    "CONTACTDOC.SHOPID": "店铺ID",
    "CONTACTDOC.FOCUSMICNO": "关注微信号",
    "CONTACTDOC.FIRSTORDER": "首次下单日期",
    "CONTACTDOC.SYNCID": "同步ID",
    "CONTACTDOC.AGEFROM": "年龄区间(从)",
    "CONTACTDOC.AGETO": "年龄区间(到)",
    "CONTACTDOC.INTRODID": "介绍人ID",
    "CONTACTDOC.SERVMANID": "服务人员ID",
    "CONTACTDOC.YEARBIRTH": "出生年份",
    "CONTACTDOC.DISECAT": "疾病类别",
    "CONTACTDOC.MEDIAFROM": "媒介来源",
    "CONTACTDOC.MEDIAKEY": "媒介关键词",
    "CONTACTDOC.MEDIAURL": "媒介链接",
    "CONTACTDOC.COMMQUAL": "沟通资质/资质",
    "CONTACTDOC.IDXUUID": "索引UUID",
    "CONTACTDOC.ZFBUSERID": "支付宝用户ID",
    "CONTACTDOC.OCCUPATION": "职业",
    "CONTACTDOC.IDCARDDATE": "身份证日期",
    # ── _cdc_state ──
    "_cdc_state.status": "同步状态(SUCCESS/ERROR/RUNNING)",
    # ── ZZERP_*_KPD_W 看板接口表公共字段 ──
    "BUSINESSID": "往来单位ID",
    "OPERATOR": "操作员",
    "DEPT": "部门",
    "STAFF": "员工",
    "SUPERBILLNO": "上级单据号",
    "SUPERBILLCODE": "上级单据编号",
    "SUPERBILLSN": "上级行号",
    "FCLS": "返程类/组合类",
    "LCLS": "零散类",
    "LSS": "领料/零散类",
    "STOREFLAG": "门店标记",
    "DESIGNATED": "是否指定",
    "TWOINVOICE": "双发票标记",
    "URGENCY": "紧急程度",
    "STORETYPE": "仓库/门店类型",
    "PLATCODE": "平台编码",
    "SHIPPER": "发货方",
    "AUDITUSER": "审核人",
    "SECAUDITUSER": "二次审核人",
    "ZT": "状态",
    "CH_ZT": "签核状态",
    "FHTBH": "发货提单号",
    "OMS_DJBH": "OMS单据编号",
    "LOGISTICSCODE": "物流编码",
    "DS_BW": "电商部位",
    "DS_ZCW": "电商账务位",
    "SIGNATURE": "签名",
    "TEMPLATEURL": "模板URL",
    "BENDIAN": "本店标识",
    "DJTYPE": "单据类型",
    "ZSHL": "总数量/收货量",
    "BQTM": "标签条码",
    "XLH": "序列号",
    "LCLCODE": "零散编码",
    "YANSHR": "验收人",
    # ── 各表零星补充 ──
    "SALEOUTDT.PROMID": "促销ID",
    "RETGOODSDT.PROMID": "促销ID",
    "RETGOODSDT.PRICEPROMID": "价格促销ID",
    "REQUESTDT.DISTBILLNO": "分配单据号",
    "REQUESTDT.DISTRNUM": "分配数量",
    "_cdc_state.STATUS": "同步状态(SUCCESS/ERROR/RUNNING)",
    "dim.staff.status": "状态(ACTIVE/INACTIVE)",
    "dim.customer.dept_id": "部门ID",
    "dim.supplier.status": "状态(ACTIVE/INACTIVE)",
    "ZBKXKC.BESALENUM": "被销售数量",
    "K_LSKC_DT.RFANGLEID": "收货货位ID",
    "K_D3OMS_ORDERREFUNDMT.REFAID": "退款申请ID",
    "K_D3OMS_ORDERREFUNDMT.desc": "退款说明/描述",
    "K_D3OMS_STOCKOUTMT_PLAN.PUSH_ACTIONTYPE": "推送动作类型(create/cancel)",
    "K_D3OMS_STOCKOUTMT_PLAN.PUSH_REASON": "推送原因(退款拦截/手动取消等)",
    # ── SALENOTESMT 最后批次 ──
    "SALENOTESMT.CONTRACTCODE": "合同号",
    "SALENOTESMT.INVOICE": "发票",
    "SALENOTESMT.DELIVERY": "配送方式",
    "SALENOTESMT.PAYTYPE": "付款方式",
    "SALENOTESMT.PAIJIA": "牌价",
    "SALENOTESMT.OPPCONTID": "机会联系人ID",
    "SALENOTESMT.PICKUPMANID": "配货员ID",
    "SALENOTESMT.WLDEPTID": "物流部门ID",
    "SALENOTESMT.BUSICATE": "业务类别",
    "SALENOTESMT.INVOREQ": "开票要求",
    "SALENOTESMT.LEVELID": "等级ID",
    "SALENOTESMT.APID": "审批流ID",
    # ── PURINDT 采购入库明细成本 ──
    "PURINDT.INCOST": "入库成本",
    "PURINDT.OUTCOST": "出库成本",
    "PURINDT.ACTPURAMT": "实际采购金额",
    "PURINDT.INACTCOST": "实际入库成本",
    "PURINDT.OUTACTCOST": "实际出库成本",
    # ── REQUESTMT 要货申请（末批） ──
    "REQUESTMT.BUSINESSNAME": "往来单位名称",
    "REQUESTMT.K_ISAPPWC": "是否审批完成扩展",
    "REQUESTMT.QH_MODEL": "签核模型",
    "REQUESTMT.QH_LEIBIE": "签核类别",
    "REQUESTMT.QH_LB": "签核类别(批)",
    # ── GOODSDOC / 其它 ──
    "GOODSDOC.LOGOGRAM": "商品简称/标识",
    "GOODSDOC.DOCLEVID": "文档层级ID",
    "GOODSDOC.DELUSERID": "删除人ID",
    "GOODSOCCU.REBILLSN": "原行号",
    "SALEOUTMT.ADDRESSID": "收货地址ID",
    "SALEOUTMT.APID": "审批流ID",
    "SALEOUTMT.CONTRACTCODE": "合同号",
    "SALEOUTMT.INVOICE": "发票",
    "SALEOUTMT.DELIVERY": "配送方式",
    "SALEOUTMT.PAYTYPE": "付款方式",
    "SALEOUTMT.PAIJIA": "牌价",
    "SALEOUTMT.OPPCONTID": "机会联系人ID",
    "SALEOUTMT.PICKUPMANID": "配货员ID",
    "SALEOUTMT.WLDEPTID": "物流部门ID",
    "SALEOUTMT.BUSICATE": "业务类别",
    "SALEOUTMT.INVOREQ": "开票要求",
    "SALEOUTMT.LEVELID": "等级ID",
    # ── GOODSATTR K_扩展字段（根据值域判别） ──
    "GOODSATTR.K_ZBZJS": "总包装件数",
    "GOODSATTR.K_WMSGROUP": "WMS货位/商品分组",
    "GOODSATTR.K_ZCPJCODE": "中药成品批件编码",
    "GOODSATTR.K_ISSHS": "是否双色盒标记",
    "GOODSATTR.K_ISPACK": "是否需包装",
    "GOODSATTR.K_ISZCPJ": "是否中药成品",
    "GOODSATTR.K_INTAXRATE": "进项税率(扩展)",
    "GOODSATTR.K_OUTTAXRATE": "销项税率(扩展)",
    "GOODSATTR.K_ISQH": "是否缺货标记",
    "GOODSATTR.K_ISSQBB": "是否统筹报销标记",
    "GOODSATTR.K_ISYYBB": "是否医保报销标记",
    "GOODSATTR.K_ISSQJP": "是否统筹价标记",
    "GOODSATTR.K_ISYYJP": "是否医保价标记",
    "GOODSATTR.K_ISTH": "是否特耗标记",
    "GOODSATTR.K_ISYFJY": "是否医保药店仅限标记",
    "GOODSATTR.K_ISETJY": "是否儿童仅限标记",
    "GOODSATTR.K_ISDBTH": "是否代包调护标记",
    "GOODSATTR.K_ISBDB": "是否不代报标记",
    "GOODSATTR.K_ISYWF": "是否验物价标记",
    "GOODSATTR.K_CGSX": "采购属性(活动取消/政策取消等)",
    "GOODSATTR.K_XDSX": "协定属性/选单属性",
    "GOODSATTR.K_DSPT": "是否电视/平台销售标记",
    "GOODSATTR.K_ISLONG": "是否长效标记",
    "GOODSATTR.K_XZYY": "是否限制用药标记",
    "GOODSATTR.K_TS": "天数(扩展)",
    "GOODSATTR.K_PZCGY": "品种采购员(A/B)",
    "GOODSATTR.K_ISYPBZ": "是否医保备证标记",
    "GOODSATTR.K_ISSMS": "是否短信标记",
    "GOODSATTR.K_ISHXPZ": "是否海报品种标记",
    "GOODSATTR.K_WLLB": "物流类别",
    "GOODSATTR.K_JYSX": "交易属性/结算方式(现款/月结等)",
    "GOODSATTR.K_ISJJSP": "是否紧急审批标记",
    "GOODSATTR.K_ISFML": "是否复方类标记",
    "GOODSATTR.K_ISLD": "是否联动标记",
    "GOODSATTR.K_ISTJ": "是否特价标记",
    "GOODSATTR.K_XSQD": "销售清单标记",
    "GOODSATTR.K_GWJ": "挂网价/供应价",
    # SALEOUTDT 销售出库明细
    "SALEOUTDT.BILLNO": "主表单据号(外键->SALEOUTMT)",
    "SALEOUTDT.BILLSN": "明细行号",
    "SALEOUTDT.GOODSID": "商品ID",
    "SALEOUTDT.GOODSNAME": "商品名称",
    "SALEOUTDT.WHID": "仓库ID",
    "SALEOUTDT.NUM": "销售数量",
    "SALEOUTDT.PRICE": "单价",
    "SALEOUTDT.TAXPRICE": "含税单价",
    "SALEOUTDT.AMOUNT": "金额(不含税)",
    "SALEOUTDT.TAXAMOUNT": "含税金额",
    "SALEOUTDT.COSTAMT": "成本金额",
    "SALEOUTDT.PROFIT": "毛利",
    "SALEOUTDT.BATCHCODE": "批号",
    "SALEOUTDT.VALDATE": "有效期至",
    "SALEOUTDT.PRODUCEDATE": "生产日期",
    "SALEOUTDT.DS_PRICE": "电商售价",
    "SALEOUTDT.DS_AMOUNT": "电商销售金额(平台实际)",
    "SALEOUTDT.UNIT": "单位",
    "SALEOUTDT.MEAS": "包装换算率",
    "SALEOUTDT.RETAILP": "零售价",
    "SALEOUTDT.ISFREE": "是否赠送",
    "SALEOUTDT.ISINVOICE": "是否开票",
    "SALEOUTDT.CHBILLNO": "差错单据号",
    "SALEOUTDT.CHBILLSN": "差错行号",
    "SALEOUTDT.ADJRATE": "调整率",
    "SALEOUTDT.ADJPRICE": "调整价",
    "SALEOUTDT.ISADJ": "是否有调整",
    "SALEOUTDT.ADJNUM": "调整数量",
    # GOODSDOC 商品档案
    "GOODSDOC.GOODSID": "商品ID",
    "GOODSDOC.GOODSNAME": "商品名称",
    "GOODSDOC.GOODSCODE": "商品编码",
    "GOODSDOC.GOODSSPEC": "规格",
    "GOODSDOC.PLACE": "产地",
    "GOODSDOC.MANUFACTURER": "生产企业",
    "GOODSDOC.BARCODE": "条形码",
    "GOODSDOC.BRANDID": "品牌ID",
    "GOODSDOC.GOODSDESC": "商品描述",
    "GOODSDOC.UNITS": "单位",
    "GOODSDOC.B2C_CODE": "B2C商城编码",
    "GOODSDOC.K_SPBH": "商品编号扩展",
    # BATCHCODE 批次
    "BATCHCODE.GOODSID": "商品ID",
    "BATCHCODE.BATCHCODE": "批号",
    "BATCHCODE.PRODUCEDATE": "生产日期",
    "BATCHCODE.VALDATE": "有效期至",
    "BATCHCODE.PURP": "采购价",
    "BATCHCODE.PURTAXP": "含税采购价",
    "BATCHCODE.SALEP": "销售价",
    "BATCHCODE.SALETAXP": "含税销售价",
    "BATCHCODE.RETAILP": "零售价",
    "BATCHCODE.SUPPLIERSID": "供应商ID",
    "BATCHCODE.APPROVALNO": "批准文号",
    "BATCHCODE.PLACE": "产地",
    "BATCHCODE.ISSALE": "是否可售",
    "BATCHCODE.ISPROCUR": "是否可采购",
    "BATCHCODE.ISFREEZE": "是否冻结",
    "BATCHCODE.BEACTIVE": "是否启用",
    "BATCHCODE.ANGLECODE": "货位编码",
    # ANGLEBALANCE 库存
    "ANGLEBALANCE.GOODSID": "商品ID",
    "ANGLEBALANCE.LOCATID": "库位ID",
    "ANGLEBALANCE.ANGLEID": "货位ID",
    "ANGLEBALANCE.PLACENUM": "当前库存数量",
    "ANGLEBALANCE.PLACEPACK": "货位包装件数",
    "ANGLEBALANCE.STORMAX": "最大库存",
    "ANGLEBALANCE.STORMIN": "最小库存(预警阈值)",
    "ANGLEBALANCE.STORFIT": "合理库存",
    "ANGLEBALANCE.MIDNUM": "中间单位数量",
    "ANGLEBALANCE.OCCUPNUM": "占用数量",
    "ANGLEBALANCE.SALESSTATE": "销售状态",
    "ANGLEBALANCE.CURINGDATE": "养护日期",
    # 电商退款
    "K_D3OMS_ORDERREFUNDMT.ERP_ORDER_ID": "ERP订单ID",
    "K_D3OMS_ORDERREFUNDMT.REFUNDFEE": "退款金额",
    "K_D3OMS_ORDERREFUNDMT.STATUS": "状态",
    "K_D3OMS_ORDERREFUNDMT.REASON": "退款原因",
    "K_D3OMS_ORDERREFUNDMT.REFOID": "平台退款单号",
    "K_D3OMS_ORDERREFUNDMT.ORDERSTATUS": "订单状态",
    "K_D3OMS_ORDERREFUNDMT.REFUNDPHASE": "退款阶段",
    "K_D3OMS_ORDERREFUNDMT.LOGISTICSCOMPANY": "物流公司",
    "K_D3OMS_ORDERREFUNDMT.LOGISTICSORDERNO": "物流单号",
    "K_D3OMS_ORDERREFUNDMT.TYPE": "退款类型",
    "K_D3OMS_ORDERREFUNDMT.TOTALFEE": "订单总金额",
    "K_D3OMS_ORDERREFUNDMT.DEPTNAME": "部门名称",
    # 电商出库计划
    "K_D3OMS_STOCKOUTMT_PLAN.ERP_ORDER_ID": "ERP订单ID",
    "K_D3OMS_STOCKOUTMT_PLAN.POSNAME": "店铺名称",
    "K_D3OMS_STOCKOUTMT_PLAN.PROVINCE": "省份",
    "K_D3OMS_STOCKOUTMT_PLAN.CITY": "城市",
    "K_D3OMS_STOCKOUTMT_PLAN.DISTRICT": "区县",
    "K_D3OMS_STOCKOUTMT_PLAN.WAREHOUSECODE": "仓库编码",
    "K_D3OMS_STOCKOUTMT_PLAN.WAREHOUSENAME": "仓库名称",
    "K_D3OMS_STOCKOUTMT_PLAN.PLANTYPE": "计划类型",
    "K_D3OMS_STOCKOUTMT_PLAN.SELLERMEMO": "卖家备注",
    "K_D3OMS_STOCKOUTMT_PLAN.BUYERMEMO": "买家备注",
    "K_D3OMS_STOCKOUTMT_PLAN.SOURCEPLATFORMTYPE": "来源平台类型",
    "K_D3OMS_STOCKOUTMT_PLAN.SOURCECODE": "来源编码",
    "K_D3OMS_STOCKOUTMT_PLAN.LOGISTICSCODE": "物流编码",
    "K_D3OMS_STOCKOUTMT_PLAN.LOGISTICSNAME": "物流公司",
    "K_D3OMS_STOCKOUTMT_PLAN.EXPRESSCODE": "快递单号",
    "K_D3OMS_STOCKOUTMT_PLAN.PAYTIME": "付款时间",
    "K_D3OMS_STOCKOUTMT_PLAN.ISDONE": "是否完成",
    "K_D3OMS_STOCKOUTMT_PLAN.BUSINESSTYPE": "业务类型",
    "K_D3OMS_STOCKOUTMT_PLAN.ZT": "状态",
    "K_D3OMS_STOCKOUTMT_PLAN.INCREMENTFLAG": "增量标记",
    # dim
    "product.product_id": "商品ID(主键)",
    "product.product_code": "商品编码",
    "product.product_name": "商品名称",
    "product.short_name": "简称",
    "product.specification": "规格",
    "product.manufacturer": "生产厂家",
    "product.barcode": "条形码",
    "product.unit": "单位",
    "product.status": "状态(ACTIVE/INACTIVE/FROZEN/ABANDONED)",
    "customer.customer_id": "客户ID(主键)",
    "customer.customer_code": "客户编码",
    "customer.customer_type": "客户类型",
    "customer.status": "状态(ACTIVE/INACTIVE/ABANDONED)",
    "warehouse.warehouse_id": "仓库ID",
    "warehouse.warehouse_code": "仓库编码",
    "warehouse.warehouse_name": "仓库名称",
    "warehouse.status": "状态",
    # agg
    "daily_sales.sale_date": "销售日期",
    "daily_sales.warehouse_id": "仓库ID",
    "daily_sales.customer_id": "客户ID",
    "daily_sales.product_id": "商品ID",
    "daily_sales.order_count": "订单数",
    "daily_sales.total_qty": "销售数量",
    "daily_sales.total_amount": "销售金额",
    "daily_sales.total_cost": "销售成本",
    "daily_sales.gross_profit": "毛利",
    "daily_sales.gross_margin": "毛利率",
    "daily_sales.etl_time": "ETL同步时间",
    "alert_inventory.alert_date": "预警日期",
    "alert_inventory.alert_time": "预警时间",
    "alert_inventory.warehouse_id": "仓库ID",
    "alert_inventory.product_id": "商品ID",
    "alert_inventory.product_name": "商品名称",
    "alert_inventory.alert_type": "预警类型",
    "alert_inventory.current_qty": "当前库存",
    "alert_inventory.threshold_qty": "预警阈值",
    "alert_inventory.severity": "严重程度(高/中/低)",
    "alert_inventory.status": "状态",
    "alert_inventory.etl_time": "ETL同步时间",
    "data_audit.audit_date": "对账日期",
    "data_audit.table_name": "表名",
    "data_audit.source_count": "源(Oracle)行数",
    "data_audit.target_count": "目标(DuckDB)行数",
    "data_audit.diff_count": "差异行数",
    "data_audit.status": "对账状态",
    "data_audit.error_detail": "错误详情",
    "data_audit.etl_time": "ETL同步时间",
    "kpi_realtime.metric_date": "指标日期",
    "kpi_realtime.metric_hour": "指标小时",
    "kpi_realtime.metric_name": "指标名称",
    "kpi_realtime.metric_value": "指标值",
    "kpi_realtime.metric_unit": "指标单位",
    "kpi_realtime.yoy_value": "同比值",
    "kpi_realtime.mom_value": "环比值",
    "kpi_realtime.target_value": "目标值",
    "kpi_realtime.achievement_rate": "达成率",
    "kpi_realtime.update_time": "更新时间",
    "weekly_report.week_start": "周开始日期",
    "weekly_report.week_end": "周结束日期",
    "weekly_report.metric_name": "指标名称",
    "weekly_report.metric_value": "指标值",
    "weekly_report.yoy_value": "同比值",
    "weekly_report.wow_value": "环比值(周同比)",
    "weekly_report.etl_time": "ETL同步时间",
    "monthly_report.month_start": "月初日期",
    "monthly_report.month_end": "月末日期",
    "monthly_report.metric_name": "指标名称",
    "monthly_report.metric_value": "指标值",
    "monthly_report.yoy_value": "同比值",
    "monthly_report.mom_value": "环比值(月环比)",
    "monthly_report.etl_time": "ETL同步时间",
    # c_retail_detail 零售明细宽表
    "c_retail_detail.BILLNO": "主表单据号",
    "c_retail_detail.ENTID": "企业ID/账套标识",
    "c_retail_detail.BILLCODE": "单据编号",
    "c_retail_detail.RULEID": "单据规则ID",
    "c_retail_detail.sale_date": "销售日期",
    "c_retail_detail.sale_time": "销售时间",
    "c_retail_detail.CLIENTID": "客户ID",
    "c_retail_detail.SALECLIENTID": "销售客户ID",
    "c_retail_detail.SALEMANID": "业务员ID",
    "c_retail_detail.ORGID": "组织ID",
    "c_retail_detail.CLIENTCODE": "客户编码",
    "c_retail_detail.BUSINESSNAME": "往来单位名称",
    "c_retail_detail.BILLSN": "明细行号",
    "c_retail_detail.GOODSID": "商品ID",
    "c_retail_detail.PACKID": "包装ID",
    "c_retail_detail.MEAS": "包装含量/换算率",
    "c_retail_detail.UNIT": "单位",
    "c_retail_detail.BASENUM": "基本单位数量",
    "c_retail_detail.RATE": "税率",
    "c_retail_detail.NUM": "数量",
    "c_retail_detail.REMARK": "备注",
    "c_retail_detail.GOODSCODE": "商品编码",
    "c_retail_detail.GOODSNAME": "商品名称",
    "c_retail_detail.GOODSSPEC": "商品规格",
    "c_retail_detail.PLACE": "产地",
    "c_retail_detail.MANUFACTURER": "生产企业",
    "c_retail_detail.WHNAME": "仓库名称",
    "c_retail_detail.locatname": "库位名称",
    "c_retail_detail.OWNERID": "所有者ID",
    "c_retail_detail.WHORGID": "仓库组织ID",
    "c_retail_detail.WHID": "仓库ID",
    "c_retail_detail.LOCATID": "库位ID",
    "c_retail_detail.BATCHCODE": "批号",
    "c_retail_detail.PRODUCEDATE": "生产日期",
    "c_retail_detail.VALDATE": "有效期至",
    "c_retail_detail.sterilcode": "灭菌批号",
    "c_retail_detail.orgname": "组织名称",
    "c_retail_detail.salemanname": "业务员名称",
    "c_retail_detail.caozyname": "操作员名称",
    "c_retail_detail.staffname1": "员工姓名1",
    "c_retail_detail.ds_price": "电商售价",
    "c_retail_detail.ds_amount": "电商销售金额",
    "c_retail_detail.ys_amount": "应收金额",
    "c_retail_detail.taxprofit": "含税毛利",
    "c_retail_detail.COSTAMT": "成本金额",
    "c_retail_detail.taxcostamt": "含税成本金额",
    "c_retail_detail.net_amount": "净额",
    "c_retail_detail.net_profit": "净利润",
    "c_retail_detail.profitrate": "毛利率",
    "c_retail_detail.POSNAME": "店铺名称",
    "c_retail_detail.ORDERID": "电商订单ID",
    "c_retail_detail.platform_order_no": "平台订单号",
    "c_retail_detail.so_id": "销售单ID",
    "c_retail_detail.logisticsno": "物流单号",
    "c_retail_detail.K_XSLB": "销售类别",
    "c_retail_detail.b2c_fl": "B2C分类",
    "c_retail_detail.b2c_cgy": "B2C采购类目",
    "c_retail_detail.b2c_beian": "B2C备案号",
    "c_retail_detail.ONECATNAME": "一级类目名称",
    "c_retail_detail.RECIPETYPE": "处方类型(处方/OTC等)",
    "c_retail_detail.GENERALNAME": "通用名",
    "c_retail_detail.agg_trace_codes": "追溯码聚合",
    "c_retail_detail.bill_type": "单据类型",
    "c_retail_detail._etl_time": "ETL同步时间",
}

# ---------------- 通用多选/单选状态值解释（可选增强提示） ----------------
VALUE_HINTS = {
    "IS": {"Y": "是", "N": "否", "1": "是", "0": "否"},
    "STATUS": {"ACTIVE": "启用", "INACTIVE": "停用", "FROZEN": "冻结", "ABANDONED": "作废", "SUCCESS": "成功", "ERROR": "错误", "RUNNING": "运行中"},
}


def translate_field(field_name: str) -> str:
    """根据字段名自动推断中文备注（未匹配则返回空串）"""
    upper = field_name.upper()

    # 1. 精确覆盖
    if upper in _COMMON_FIELD_MAP:
        return _COMMON_FIELD_MAP[upper]

    # 2. K_ 扩展字段
    if upper in K_EXTRA:
        return K_EXTRA[upper]

    # 3. IS 开头标志 -> "是否XXX"
    if upper.startswith("IS") and len(upper) > 2:
        rest = upper[2:]
        # 尝试翻译剩余部分
        rest_cn = _partial_translate(rest)
        if rest_cn:
            return f"是否{rest_cn}"
        return f"是否{_readable(rest)}"

    # 4. 含下划线的驼峰/多词拆分翻译
    if "_" in field_name or _has_camel(field_name):
        parts = _split_words(field_name)
        cns = []
        for p in parts:
            pu = p.upper()
            if pu in _COMMON_FIELD_MAP:
                cns.append(_COMMON_FIELD_MAP[pu])
            elif pu in K_EXTRA:
                cns.append(K_EXTRA[pu])
            else:
                cns.append(_readable(p))
        # 若全部未翻译（无一命中词典），则放弃返回空，避免无意义串
        hit = any(p.upper() in _COMMON_FIELD_MAP or p.upper() in K_EXTRA for p in parts)
        if not hit:
            return ""
        return "".join(cns)

    return ""


def _has_camel(s: str) -> bool:
    """判断是否存在驼峰（小写后跟大写字母）"""
    for i in range(1, len(s)):
        if s[i].isupper() and s[i - 1].islower():
            return True
    return False


def _split_words(s: str) -> list:
    """把字段名拆成单词：既处理下划线也处理驼峰，如 sale_date -> [sale,date]，etlTime -> [etl,time]"""
    import re
    # 先按下划线拆，再在每个片段里按驼峰拆
    words = []
    for seg in s.split("_"):
        if not seg:
            continue
        # 驼峰拆分: SaleDate -> [Sale, Date]
        sub = re.findall(r"[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+|[A-Z]+", seg)
        words.extend(sub)
    return words


def _partial_translate(s: str) -> str:
    """翻译 IS 前缀后的词干"""
    if s in _COMMON_FIELD_MAP:
        return _COMMON_FIELD_MAP[s]
    # 常见尾部
    for k, v in [("TAX", "税"), ("FREEZE", "冻结"), ("ABANDON", "作废"),
                 ("ACTIVE", "启用"), ("SALE", "销售"), ("PROCUR", "采购"),
                 ("DONE", "完成"), ("VALID", "有效"), ("REFRIG", "冷藏"),
                 ("MEDICARE", "医保"), ("DRUG", "药品"), ("OTC", "OTC"),
                 ("TRACE", "追溯"), ("INVOICE", "开票"), ("FREE", "赠送"),
                 ("PRES", "处方"), ("ELEC", "电商"), ("WMS", "WMS")]:
        if s == k or s.endswith(k):
            return v
    return ""


def _readable(s: str) -> str:
    """把英文缩写转成可读形式（保留原样）"""
    # 常见缩写
    abbr = {"MT": "主表", "DT": "明细", "ID": "ID", "NO": "单号", "NUM": "数量",
            "AMT": "金额", "PRICE": "价", "QTY": "数量"}
    if s in abbr:
        return abbr[s]
    return s
