-- ============================================
-- 医药电商数据仓库 - DuckDB Raw 层重建
-- 基于 Oracle RACE Schema 实际表结构
-- 2026-07-22
-- ============================================

-- 清除旧 raw 表
DROP TABLE IF EXISTS raw.orders;
DROP TABLE IF EXISTS raw.order_lines;
DROP TABLE IF EXISTS raw.inventory;
DROP TABLE IF EXISTS raw._cdc_state;

-- ============================================
-- raw._cdc_state - CDC 同步状态表
-- ============================================
CREATE TABLE raw._cdc_state (
    table_name VARCHAR PRIMARY KEY,
    last_cdc_time VARCHAR,           -- Oracle 侧最后同步时间（CHAR 格式保持原样）
    last_cdc_ts TIMESTAMP,           -- 转换后的时间戳
    last_record_count BIGINT,
    last_sync_time TIMESTAMP,
    status VARCHAR,                  -- SUCCESS / RUNNING / ERROR
    error_msg VARCHAR,
    sync_mode VARCHAR DEFAULT 'INCREMENTAL'  -- FULL / INCREMENTAL
);

-- ============================================
-- raw.SALEOUTMT - 销售出库主表 (65.5万行)
-- ============================================
CREATE TABLE raw.SALEOUTMT (
    BILLNO BIGINT,
    ENTID VARCHAR,
    BILLCODE VARCHAR,
    RULEID VARCHAR,
    DATES VARCHAR,                   -- CHAR 类型，YYYY-MM-DD HH:MM:SS
    ONTIME VARCHAR,
    SYSDATES VARCHAR,
    ISVAT VARCHAR,
    CLIENTID VARCHAR,
    ACCPTID VARCHAR,
    SALEMANID VARCHAR,
    PAYORGID VARCHAR,
    CAOZY VARCHAR,
    ORGID VARCHAR,
    DEPTID VARCHAR,
    CONTRACTCODE VARCHAR,
    INVOICE VARCHAR,
    DELIVERY VARCHAR,
    PAYTYPE VARCHAR,
    AMOUNT DECIMAL(18,4),
    TAX DECIMAL(18,4),
    TAXAMOUNT DECIMAL(18,4),
    PROFIT DECIMAL(18,4),
    RETAILAMT DECIMAL(18,4),
    SUMMARIES VARCHAR,
    REMARK VARCHAR,
    SALECLIENTID VARCHAR,
    DEDRATE DECIMAL(10,4),
    COSTAMT DECIMAL(18,4),
    REQDATE VARCHAR,
    CURRENCYID VARCHAR,
    PAIJIA DECIMAL(18,4),
    ISINVOICE VARCHAR,
    ISDONE VARCHAR,
    CURCODE VARCHAR,
    ADDRESS VARCHAR,
    ISCH VARCHAR,
    ISCHWC VARCHAR,
    OPPCONTID VARCHAR,
    PICKUPMANID VARCHAR,
    ADDRESSID VARCHAR,
    RECEMANID VARCHAR,
    WLDEPTID VARCHAR,
    SREASON VARCHAR,
    INVOICEAMT DECIMAL(18,4),
    ISHTFH VARCHAR,
    ISHZFH VARCHAR,
    ACTCOSTAMT DECIMAL(18,4),
    ACTPROFIT DECIMAL(18,4),
    BUSICATE DECIMAL(10,2),
    INVOREQ DECIMAL(10,2),
    ZJNUM DECIMAL(18,4),
    LSNUM DECIMAL(18,4),
    FHYID VARCHAR,
    SECACCEPTID VARCHAR,
    BILLTYPE VARCHAR,
    ORDERID VARCHAR,
    INVOICETYPE VARCHAR,
    K_KDGS VARCHAR,                  -- 快递公司
    K_KDLXR VARCHAR,                -- 快递联系人
    K_KDLXDH VARCHAR,               -- 快递联系电话
    K_KDLXDZ VARCHAR,               -- 快递联系地址
    B2BTYPE VARCHAR,
    B2BCODE VARCHAR,
    K_ISREPORT VARCHAR,
    K_ISPJ VARCHAR,
    K_ISWTS VARCHAR,
    K_KDDH VARCHAR,                 -- 快递单号
    K_KPBILLNO DECIMAL,
    K_KPBILLCODE VARCHAR,
    K_KPYID VARCHAR,
    K_KPY VARCHAR,
    K_FHY VARCHAR,                  -- 发货员
    K_KDDYRQ VARCHAR,               -- 快递打印日期
    ISTRACE VARCHAR,
    ACCEPTID VARCHAR,
    K_SHR VARCHAR,                  -- 收货人
    PZID VARCHAR,
    KJ_YEAR VARCHAR,
    KJ_MONTH VARCHAR,
    POSNAME VARCHAR,
    REFOID VARCHAR,                 -- 关联订单号（电商平台订单号）
    LOGISTICSNO VARCHAR,
    DSCODE VARCHAR,
    DSTYPE VARCHAR,
    IS_DSTH VARCHAR,
    K_PROVINCE VARCHAR,
    K_CITY VARCHAR,
    K_AREA VARCHAR,
    K_ISDB VARCHAR,
    APID VARCHAR,
    -- ETL 元数据
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.SALEOUTDT - 销售出库明细 (84.3万行)
-- ============================================
CREATE TABLE raw.SALEOUTDT (
    BILLNO BIGINT,
    BILLSN DECIMAL,
    ENTID VARCHAR,
    BILLSORT DECIMAL,
    GOODSID VARCHAR,
    OWNERID VARCHAR,
    PACKID VARCHAR,
    MEAS DECIMAL(18,4),
    LOCATID VARCHAR,
    ANGLEID VARCHAR,
    BASENUM DECIMAL(18,4),
    NUM DECIMAL(18,4),
    DEDRATE DECIMAL(10,4),
    AMOUNT DECIMAL(18,4),
    RATE DECIMAL(10,4),
    TAX DECIMAL(18,4),
    TAXAMOUNT DECIMAL(18,4),
    RETAILP DECIMAL(18,4),
    COSTAMT DECIMAL(18,4),
    ISFREE VARCHAR,
    OUTCOST DECIMAL(18,4),
    RFBILLNO DECIMAL,
    RFBILLSN DECIMAL,
    REBILLNO DECIMAL,
    REBILLSN DECIMAL,
    REMARK VARCHAR,
    WHID VARCHAR,                    -- 仓库ID
    PROFIT DECIMAL(18,4),
    WHORGID VARCHAR,
    ISINVOICE VARCHAR,
    INVOICENUM DECIMAL(18,4),
    INVOICEAMT DECIMAL(18,4),
    RFBILLCODE VARCHAR,
    REBILLCODE VARCHAR,
    COST DECIMAL(18,4),
    NEWPRICE DECIMAL(18,4),
    OLDPRICE DECIMAL(18,4),
    PRICE DECIMAL(18,4),
    BASEPRICE DECIMAL(18,4),
    TAXPRICE DECIMAL(18,4),
    BASETAXPRICE DECIMAL(18,4),
    OLDTAXPRICE DECIMAL(18,4),
    NEWTAXPRICE DECIMAL(18,4),
    RFRULEID VARCHAR,
    RERULEID VARCHAR,
    ISDONE VARCHAR,
    RETURNNUM DECIMAL(18,4),
    FIXAMT DECIMAL(18,4),
    UNIT VARCHAR,
    CHNUM DECIMAL(18,4),
    CHBILLNO DECIMAL,
    CHBILLSN DECIMAL,
    ISCHWC VARCHAR,
    PROMID VARCHAR,
    GRPNO DECIMAL,
    ADJRATE DECIMAL(10,4),
    ADJPRICE DECIMAL(18,4),
    ISADJ VARCHAR,
    ADJNUM DECIMAL(18,4),
    CONTRACTID VARCHAR,
    APID VARCHAR,
    SUPPLIERSID VARCHAR,
    ACTCOSTAMT DECIMAL(18,4),
    CHECKCOST DECIMAL(18,4),
    ACTPROFIT DECIMAL(18,4),
    ACTPRICE DECIMAL(18,4),
    ACTTAXPRICE DECIMAL(18,4),
    ACTAMOUNT DECIMAL(18,4),
    OLDACTPRICE DECIMAL(18,4),
    NEWACTPRICE DECIMAL(18,4),
    OLDACTTAXPRICE DECIMAL(18,4),
    NEWACTTAXPRICE DECIMAL(18,4),
    OUTACTCOST DECIMAL(18,4),
    RETAILAMT DECIMAL(18,4),
    BATCHNO DECIMAL,
    K_RETURNNUM DECIMAL(18,4),
    BATCHCODE VARCHAR,               -- 批号
    VALDATE VARCHAR,                 -- 有效期
    PRODUCEDATE VARCHAR,             -- 生产日期
    DS_PRICE DECIMAL(18,4),
    DS_AMOUNT DECIMAL(18,4),
    IS_DSTH VARCHAR,
    -- ETL 元数据
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.SALENOTESMT - 销售单主表 (66.5万行)
-- ============================================
CREATE TABLE raw.SALENOTESMT (
    BILLNO DECIMAL,
    ENTID VARCHAR,
    BILLCODE VARCHAR,
    RULEID VARCHAR,
    DATES VARCHAR,
    ONTIME VARCHAR,
    SYSDATES VARCHAR,
    ISVAT VARCHAR,
    CLIENTID VARCHAR,
    DEDRATE DECIMAL(10,4),
    ACCPTID VARCHAR,
    ADDRESS VARCHAR,
    PAYORGID VARCHAR,
    SALEMANID VARCHAR,
    CAOZY VARCHAR,
    ORGID VARCHAR,
    DEPTID VARCHAR,
    CONTRACTCODE VARCHAR,
    INVOICE VARCHAR,
    DELIVERY VARCHAR,
    PAYTYPE VARCHAR,
    ISEND VARCHAR,
    SUMMARIES VARCHAR,
    REMARK VARCHAR,
    SALECLIENTID VARCHAR,
    CURRENCYID VARCHAR,
    PAIJIA DECIMAL(18,4),
    ISSETTLE VARCHAR,
    ISAD VARCHAR,
    ADVAMT DECIMAL(18,4),
    ISDONE VARCHAR,
    BILLSTATE DECIMAL,
    OPPCONTID VARCHAR,
    PICKUPMANID VARCHAR,
    GOODSGLIST VARCHAR,
    OLDBILLNO DECIMAL,
    ADDRESSID VARCHAR,
    WLDEPTID VARCHAR,
    SREASON VARCHAR,
    BUSICATE DECIMAL(10,2),
    INVOREQ DECIMAL(10,2),
    BILLSRC DECIMAL,
    LEVELID VARCHAR,
    TPLBILLID VARCHAR,
    TPLDOCID VARCHAR,
    BILLTYPE VARCHAR,
    BUSINESSNAME VARCHAR,
    ORDERID VARCHAR,
    IS_WMS VARCHAR,
    YWTYPE VARCHAR,
    DSCODE VARCHAR,
    DSTYPE VARCHAR,
    B2BCODE VARCHAR,
    POSNAME VARCHAR,
    LOGISTICSNO VARCHAR,
    REFOID VARCHAR,
    IS_WMSHD VARCHAR,
    K_KDGS VARCHAR,
    K_KDLXR VARCHAR,
    K_KDLXDZ VARCHAR,
    K_PROVINCE VARCHAR,
    K_CITY VARCHAR,
    K_AREA VARCHAR,
    K_KDLXDH VARCHAR,
    MD_STAFFNAME VARCHAR,
    MD_DATES VARCHAR,
    K_ISWTS VARCHAR,
    K_ISPJ VARCHAR,
    K_ISREPORT VARCHAR,
    APID VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.SALENOTESDT - 销售单明细 (86.5万行)
-- ============================================
CREATE TABLE raw.SALENOTESDT (
    BILLNO DECIMAL,
    BILLSN DECIMAL,
    ENTID VARCHAR,
    BILLSORT DECIMAL,
    OWNERID VARCHAR,
    GOODSID VARCHAR,
    PACKID VARCHAR,
    MEAS DECIMAL(18,4),
    LOCATID VARCHAR,
    ANGLEID VARCHAR,
    BATCHCODE VARCHAR,
    PRODUCEDATE VARCHAR,
    VALDATE VARCHAR,
    NUM DECIMAL(18,4),
    PRICE DECIMAL(18,4),
    TAXPRICE DECIMAL(18,4),
    BASENUM DECIMAL(18,4),
    DEDRATE DECIMAL(10,4),
    AMOUNT DECIMAL(18,4),
    RATE DECIMAL(10,4),
    TAX DECIMAL(18,4),
    TAXAMOUNT DECIMAL(18,4),
    PROFIT DECIMAL(18,4),
    RETAILP DECIMAL(18,4),
    ISFREE VARCHAR,
    OLDPRICE DECIMAL(18,4),
    NEWPRICE DECIMAL(18,4),
    OLDTAXPRICE DECIMAL(18,4),
    NEWTAXPRICE DECIMAL(18,4),
    SOLDNUM DECIMAL(18,4),
    NOTSOLDNUM DECIMAL(18,4),
    OUTCOST DECIMAL(18,4),
    RFBILLNO DECIMAL,
    RFBILLSN DECIMAL,
    REBILLNO DECIMAL,
    REBILLSN DECIMAL,
    REMARK VARCHAR,
    WHID VARCHAR,
    WHORGID VARCHAR,
    BASEPRICE DECIMAL(18,4),
    BASETAXPRICE DECIMAL(18,4),
    RFBILLCODE VARCHAR,
    REBILLCODE VARCHAR,
    ISDONE VARCHAR,
    RFRULEID VARCHAR,
    RERULEID VARCHAR,
    UNIT VARCHAR,
    COST DECIMAL(18,4),
    PROMID VARCHAR,
    GRPNO DECIMAL,
    STERILCODE VARCHAR,
    SUPPLIERSID VARCHAR,
    CHECKCOST DECIMAL(18,4),
    ACTPROFIT DECIMAL(18,4),
    ACTPRICE DECIMAL(18,4),
    ACTTAXPRICE DECIMAL(18,4),
    ACTAMOUNT DECIMAL(18,4),
    OLDACTPRICE DECIMAL(18,4),
    NEWACTPRICE DECIMAL(18,4),
    OLDACTTAXPRICE DECIMAL(18,4),
    NEWACTTAXPRICE DECIMAL(18,4),
    OUTACTCOST DECIMAL(18,4),
    RETAILAMT DECIMAL(18,4),
    BTGRPID VARCHAR,
    BATCHNO DECIMAL,
    PRICEFROM VARCHAR,
    PASSUSERID VARCHAR,
    PASSEXPID VARCHAR,
    TOPKGNUM DECIMAL(18,4),
    TPLROWID VARCHAR,
    TPLDOCID VARCHAR,
    GOODSCODE VARCHAR,
    GOODSNAME VARCHAR,
    GOODSSPEC VARCHAR,
    PLACE VARCHAR,
    MANUFACTURER VARCHAR,
    GOODSREF VARCHAR,
    GENERALNAME VARCHAR,
    APPROVALNO VARCHAR,
    MARKETBY VARCHAR,
    INSTREGNO VARCHAR,
    INSTBY VARCHAR,
    DS_PRICE DECIMAL(18,4),
    IS_JGM VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.GOODSDOC - 商品档案 (5.1万行)
-- ============================================
CREATE TABLE raw.GOODSDOC (
    ENTID VARCHAR,
    GOODSID VARCHAR PRIMARY KEY,
    BRANDID VARCHAR,
    ISNEW VARCHAR,
    ISFREEZE VARCHAR,
    ISABANDON VARCHAR,
    BEACTIVE VARCHAR,
    BARCODE VARCHAR,                 -- 条形码/69码
    GOODSCODE VARCHAR,               -- 商品编码
    OLDCODE VARCHAR,
    GOODSNAME VARCHAR,               -- 商品名称
    FOREIGNNAME VARCHAR,
    SHORTNAME VARCHAR,               -- 简称
    LOGOGRAM VARCHAR,
    GOODSSPEC VARCHAR,               -- 规格
    PLACE VARCHAR,                   -- 产地
    MANUFACTURER VARCHAR,            -- 生产厂家
    GOODSDESC VARCHAR,
    CREATETIME VARCHAR,
    DOCLEVID DECIMAL,
    CREATERID VARCHAR,
    CREATERINFO VARCHAR,
    LASTMODIFYTIME VARCHAR,
    DELUSERID VARCHAR,
    DELTIME VARCHAR,
    UNITS VARCHAR,                   -- 单位
    DUIYKM VARCHAR,                  -- 对应科目
    B2C_CODE VARCHAR,
    K_SPBH VARCHAR,                  -- 商品编号
    REMARK VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.CLIENTDOC - 客户档案 (1.5万行)
-- ============================================
CREATE TABLE raw.CLIENTDOC (
    CLIENTID VARCHAR PRIMARY KEY,
    ENTID VARCHAR,
    CLIENTCODE VARCHAR,
    DUIYKM VARCHAR,
    YWYID VARCHAR,                   -- 业务员ID
    DEPTID VARCHAR,
    CREATERID VARCHAR,
    CREATERINFO VARCHAR,
    CREATETIME VARCHAR,
    BEACTIVE VARCHAR,
    LASTMODIFYTIME VARCHAR,
    ISSALE VARCHAR,
    CLIENTTYPE VARCHAR,
    CLIENTSORT VARCHAR,
    SALEMANID VARCHAR,
    ELECCODE VARCHAR,                -- 电子码
    OLDCLIENTCODE VARCHAR,
    ISABANDON VARCHAR,
    CREDIT VARCHAR,
    INVOICETYPE VARCHAR,
    ORGTYPE VARCHAR,
    DRUGSTOREID VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.SUPPLYDOC - 供应商档案 (878行)
-- ============================================
CREATE TABLE raw.SUPPLYDOC (
    SUPPLIERSID VARCHAR PRIMARY KEY,
    ENTID VARCHAR,
    GYSBH VARCHAR,                   -- 供应商编号
    DUIKM VARCHAR,
    SUPPCATE DECIMAL,                -- 供应商类别
    SUPPLEV DECIMAL,                 -- 供应商等级
    BEACTIVE VARCHAR,
    LASTMODIFYTIME VARCHAR,
    CREATETIME VARCHAR,
    ISABANDON VARCHAR,
    SUPPTYPE VARCHAR,
    ELECCODE VARCHAR,
    SUPPPROP VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.STOREHOUSE - 仓库 (9行)
-- ============================================
CREATE TABLE raw.STOREHOUSE (
    WHID VARCHAR PRIMARY KEY,
    ORGID VARCHAR,
    ENTID VARCHAR,
    WHCODE VARCHAR,
    WHNAME VARCHAR,                  -- 仓库名称
    LOGOGRAM VARCHAR,
    WHTYPE VARCHAR,                  -- 仓库类型
    BEACTIVE VARCHAR,
    DIRECTORID VARCHAR,              -- 主管ID
    LASTMODIFYTIME VARCHAR,
    CREATETIME VARCHAR,
    AREASTATE DECIMAL,
    CLIENTID VARCHAR,
    WHLEVEL DECIMAL,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.STAFFDOC - 员工档案 (60行)
-- ============================================
CREATE TABLE raw.STAFFDOC (
    STAFFID VARCHAR PRIMARY KEY,
    USERID VARCHAR,
    ENTID VARCHAR,
    STAFFCODE VARCHAR,
    STAFFNAME VARCHAR,               -- 员工姓名
    POSITIONS VARCHAR,               -- 职位
    MOBILE VARCHAR,
    ISSALEMAN VARCHAR,               -- 是否业务员
    ISPROCURMAN VARCHAR,             -- 是否采购员
    ISWARE VARCHAR,                  -- 是否仓库管理员
    BEACTIVE VARCHAR,
    GENDER VARCHAR,
    DEPTID VARCHAR,
    ORGID VARCHAR,
    LASTMODIFYTIME VARCHAR,
    CREATETIME VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.BATCHCODE - 批次批号 (61.5万行)
-- ============================================
CREATE TABLE raw.BATCHCODE (
    ANGLEID VARCHAR,
    GOODSID VARCHAR,
    ENTID VARCHAR,
    BARCODE VARCHAR,
    ANGLECODE VARCHAR,
    BATCHCODE VARCHAR,               -- 批号
    PRODUCEDATE VARCHAR,             -- 生产日期
    VALDATE VARCHAR,                 -- 有效期
    PURP DECIMAL(18,4),              -- 采购价
    PURTAXP DECIMAL(18,4),           -- 采购含税价
    SALEP DECIMAL(18,4),             -- 销售价
    SALETAXP DECIMAL(18,4),          -- 销售含税价
    RETAILP DECIMAL(18,4),           -- 零售价
    ISFREEZE VARCHAR,
    ISSALE VARCHAR,
    ISPROCUR VARCHAR,
    BEACTIVE VARCHAR,
    APPROVALNO VARCHAR,              -- 批准文号
    PLACE VARCHAR,                   -- 产地
    SUPPLIERSID VARCHAR,
    LASTMODIFYTIME VARCHAR,
    CREATETIME VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.ANGLEBALANCE - 库位库存 (2.9万行)
-- ============================================
CREATE TABLE raw.ANGLEBALANCE (
    LOCATID VARCHAR,
    GOODSID VARCHAR,
    OWNERID VARCHAR,
    ANGLEID VARCHAR,
    ENTID VARCHAR,
    PLACEPACK DECIMAL(18,4),
    PLACENUM DECIMAL(18,4),          -- 库存数量
    MIDNUM DECIMAL(18,4),
    OCCUPNUM DECIMAL(18,4),          -- 占用数量
    STORMAX DECIMAL(18,4),           -- 最大库存
    STORMIN DECIMAL(18,4),           -- 最小库存
    STORFIT DECIMAL(18,4),           -- 合理库存
    SALESSTATE DECIMAL,
    CURINGDATE VARCHAR,
    LASTMODIFYTIME VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.PURORDERMT - 采购订单主表 (4163行)
-- ============================================
CREATE TABLE raw.PURORDERMT (
    BILLNO DECIMAL,
    ENTID VARCHAR,
    BILLCODE VARCHAR,
    RULEID VARCHAR,
    DATES VARCHAR,
    ONTIME VARCHAR,
    SYSDATES VARCHAR,
    ISVAT VARCHAR,
    EXPECTDATE VARCHAR,
    SUPPLIERSID VARCHAR,
    ADDRESS VARCHAR,
    ACCPTID VARCHAR,
    CURRENCYID VARCHAR,
    SALEMANID VARCHAR,
    CAOZY VARCHAR,
    ORGID VARCHAR,
    DEPTID VARCHAR,
    CONTRACTCODE VARCHAR,
    DELIVERY VARCHAR,
    PAYTYPE VARCHAR,
    OLDERNO VARCHAR,
    ISEND VARCHAR,
    ISDONE VARCHAR,
    SUMMARIES VARCHAR,
    REMARK VARCHAR,
    PAYORGID VARCHAR,
    REQDATE VARCHAR,
    BILLSTATE DECIMAL,
    OPPCONTID VARCHAR,
    GOODSGLIST VARCHAR,
    WLDEPTID VARCHAR,
    BUSICATE DECIMAL,
    BUSINESSNAME VARCHAR,
    ORDERDATE VARCHAR,
    ISTRANS VARCHAR,
    K_YWBS VARCHAR,
    IS_WMS VARCHAR,
    BEIZHU VARCHAR,
    WHID VARCHAR,
    APID VARCHAR,
    LASTMODIFYTIME VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.PURORDERDT - 采购订单明细 (18787行)
-- ============================================
CREATE TABLE raw.PURORDERDT (
    BILLNO DECIMAL,
    BILLSN DECIMAL,
    ENTID VARCHAR,
    BILLSORT DECIMAL,
    OWNERID VARCHAR,
    GOODSID VARCHAR,
    PACKID VARCHAR,
    MEAS DECIMAL(18,4),
    BATCHCODE VARCHAR,
    PRODUCEDATE VARCHAR,
    VALDATE VARCHAR,
    BASENUM DECIMAL(18,4),
    NUM DECIMAL(18,4),
    PRICE DECIMAL(18,4),
    TAXPRICE DECIMAL(18,4),
    DEDRATE DECIMAL(10,4),
    AMOUNT DECIMAL(18,4),
    RATE DECIMAL(10,4),
    TAX DECIMAL(18,4),
    TAXAMOUNT DECIMAL(18,4),
    RETAILP DECIMAL(18,4),
    ISFREE VARCHAR,
    ISDONE VARCHAR,
    UNIT VARCHAR,
    EXECNUM DECIMAL(18,4),
    CANCELNUM DECIMAL(18,4),
    GOODSCODE VARCHAR,
    GOODSNAME VARCHAR,
    GOODSSPEC VARCHAR,
    PLACE VARCHAR,
    MANUFACTURER VARCHAR,
    GENERALNAME VARCHAR,
    APPROVALNO VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.PURINMT - 采购入库主表 (4648行)
-- ============================================
CREATE TABLE raw.PURINMT (
    BILLNO DECIMAL,
    ENTID VARCHAR,
    BILLCODE VARCHAR,
    RULEID VARCHAR,
    DATES VARCHAR,
    ONTIME VARCHAR,
    SYSDATES VARCHAR,
    ISVAT VARCHAR,
    SUPPLIERSID VARCHAR,
    ADDRESS VARCHAR,
    ACCPTID VARCHAR,
    SALEMANID VARCHAR,
    CAOZY VARCHAR,
    ORGID VARCHAR,
    DEPTID VARCHAR,
    CONTRACTCODE VARCHAR,
    INVOICE VARCHAR,
    DELIVERY VARCHAR,
    PAYTYPE VARCHAR,
    OLDERNO VARCHAR,
    AMOUNT DECIMAL(18,4),
    TAX DECIMAL(18,4),
    TAXAMOUNT DECIMAL(18,4),
    RETAILAMT DECIMAL(18,4),
    COSTAMT DECIMAL(18,4),
    PROFIT DECIMAL(18,4),
    SUMMARIES VARCHAR,
    REMARK VARCHAR,
    PAYORGID VARCHAR,
    CURRENCYID VARCHAR,
    PAIJIA DECIMAL(18,4),
    DEDRATE DECIMAL(10,4),
    ISINVOICE VARCHAR,
    ISDONE VARCHAR,
    CURCODE VARCHAR,
    OPPCONTID VARCHAR,
    ISPREPAY VARCHAR,
    PREPAYAMT DECIMAL(18,4),
    WAREMANID VARCHAR,
    ISCH VARCHAR,
    ISCHWC VARCHAR,
    WLDEPTID VARCHAR,
    ISHTFH VARCHAR,
    ACTAMOUNT DECIMAL(18,4),
    ACTPROFIT DECIMAL(18,4),
    BUSICATE DECIMAL,
    BILLTYPE VARCHAR,
    FHYID VARCHAR,
    SECACCEPTID VARCHAR,
    K_YWBS VARCHAR,
    K_SHR VARCHAR,
    ACCEPTID VARCHAR,
    BEIZHU VARCHAR,
    WHID VARCHAR,
    APID VARCHAR,
    LASTMODIFYTIME VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.PURINDT - 采购入库明细 (20196行)
-- ============================================
CREATE TABLE raw.PURINDT (
    BILLNO DECIMAL,
    BILLSN DECIMAL,
    ENTID VARCHAR,
    BILLSORT DECIMAL,
    GOODSID VARCHAR,
    OWNERID VARCHAR,
    PACKID VARCHAR,
    MEAS DECIMAL(18,4),
    WHID VARCHAR,
    LOCATID VARCHAR,
    ANGLEID VARCHAR,
    BASENUM DECIMAL(18,4),
    NUM DECIMAL(18,4),
    PRICE DECIMAL(18,4),
    TAXPRICE DECIMAL(18,4),
    DEDRATE DECIMAL(10,4),
    AMOUNT DECIMAL(18,4),
    RATE DECIMAL(10,4),
    TAX DECIMAL(18,4),
    TAXAMOUNT DECIMAL(18,4),
    COSTAMT DECIMAL(18,4),
    PROFIT DECIMAL(18,4),
    RETAILP DECIMAL(18,4),
    ISFREE VARCHAR,
    ISINVOICE VARCHAR,
    INVOICENUM DECIMAL(18,4),
    INVOICEAMT DECIMAL(18,4),
    SOLDNUM DECIMAL(18,4),
    NOTSOLDNUM DECIMAL(18,4),
    INCOST DECIMAL(18,4),
    OUTCOST DECIMAL(18,4),
    ISDONE VARCHAR,
    UNIT VARCHAR,
    BATCHCODE VARCHAR,
    VALDATE VARCHAR,
    PRODUCEDATE VARCHAR,
    ACTTAXPRICE DECIMAL(18,4),
    ACTPRICE DECIMAL(18,4),
    ACTPURAMT DECIMAL(18,4),
    ACTPROFIT DECIMAL(18,4),
    INACTCOST DECIMAL(18,4),
    OUTACTCOST DECIMAL(18,4),
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.K_D3OMS_STOCKOUTMT_PLAN - OMS出库计划 (62.4万行)
-- ============================================
CREATE TABLE raw.K_D3OMS_STOCKOUTMT_PLAN (
    ERP_ORDER_ID VARCHAR,
    OWNERID VARCHAR,
    TAG VARCHAR,
    CODE VARCHAR,
    PLANTYPE VARCHAR,
    WAREHOUSECODE VARCHAR,
    WAREHOUSENAME VARCHAR,
    PROVINCE VARCHAR,
    CITY VARCHAR,
    DISTRICT VARCHAR,
    SELLERMEMO VARCHAR,
    BUYERMEMO VARCHAR,
    REMARK VARCHAR,
    SOURCEPLATFORMTYPE VARCHAR,
    SOURCECODE VARCHAR,
    REFOID VARCHAR,
    LOGISTICSCODE VARCHAR,
    LOGISTICSNAME VARCHAR,
    EXPRESSCODE VARCHAR,
    POSNAME VARCHAR,
    PAYTIME VARCHAR,
    PUSH_ACTIONTYPE VARCHAR,
    PUSH_REASON VARCHAR,
    PUSH_TIME VARCHAR,
    CREATETIME VARCHAR,
    LASTMODIFYTIME VARCHAR,
    ISDONE VARCHAR,
    POSCODE VARCHAR,
    BUSINESSTYPE VARCHAR,
    K_F_REASON VARCHAR,
    DEPTNAME VARCHAR,
    DEPTID VARCHAR,
    INCREMENTFLAG VARCHAR,
    ZT VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.K_D3OMS_ORDERREFUNDMT - 退款主表 (2202行)
-- ============================================
CREATE TABLE raw.K_D3OMS_ORDERREFUNDMT (
    ERP_ORDER_ID VARCHAR,
    OWNERID VARCHAR,
    REFAID VARCHAR,
    REFOID VARCHAR,
    DEPTID VARCHAR,
    DEPTNAME VARCHAR,
    ORDERSTATUS VARCHAR,
    REFUNDPHASE VARCHAR,
    LOGISTICSORDERNO VARCHAR,
    LOGISTICSCOMPANY VARCHAR,
    TYPE VARCHAR,
    TOTALFEE DECIMAL(18,4),
    REFUNDFEE DECIMAL(18,4),
    UPDATETIME VARCHAR,
    STATUS VARCHAR,
    REASON VARCHAR,
    "desc" VARCHAR,                  -- Oracle 保留字，加引号
    LASTMODIFYTIME VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- ============================================
-- raw.K_D3OMS_ORDERREFUNDDT - 退款明细 (2234行)
-- ============================================
CREATE TABLE raw.K_D3OMS_ORDERREFUNDDT (
    ERP_ORDER_ID VARCHAR,
    OWNERID VARCHAR,
    ERP_ORDER_SN DECIMAL,
    REFAID VARCHAR,
    REFOID VARCHAR,
    REFSPUID VARCHAR,
    REFSKUID VARCHAR,
    OUTERID VARCHAR,
    TITLE VARCHAR,
    NUM DECIMAL(18,4),
    PRICE DECIMAL(18,4),
    TOTALFEE DECIMAL(18,4),
    REFUNDFEE DECIMAL(18,4),
    LASTMODIFYTIME VARCHAR,
    _etl_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _etl_source VARCHAR DEFAULT 'ORACLE_RACE'
);

-- 完成
SELECT 'Raw schema rebuilt successfully' AS result;
